// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: auth_identity.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─────────────────────────  ENUMS  ──────────────────────────
type AccountProvider int32

const (
	AccountProvider_ACCOUNT_PROVIDER_UNSPECIFIED AccountProvider = 0
	AccountProvider_EMAIL                        AccountProvider = 1
	AccountProvider_GOOGLE                       AccountProvider = 2
)

// Enum value maps for AccountProvider.
var (
	AccountProvider_name = map[int32]string{
		0: "ACCOUNT_PROVIDER_UNSPECIFIED",
		1: "EMAIL",
		2: "GOOGLE",
	}
	AccountProvider_value = map[string]int32{
		"ACCOUNT_PROVIDER_UNSPECIFIED": 0,
		"EMAIL":                        1,
		"GOOGLE":                       2,
	}
)

func (x AccountProvider) Enum() *AccountProvider {
	p := new(AccountProvider)
	*p = x
	return p
}

func (x AccountProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_identity_proto_enumTypes[0].Descriptor()
}

func (AccountProvider) Type() protoreflect.EnumType {
	return &file_auth_identity_proto_enumTypes[0]
}

func (x AccountProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountProvider.Descriptor instead.
func (AccountProvider) EnumDescriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{0}
}

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_PENDING                    AccountStatus = 1
	AccountStatus_ACTIVE                     AccountStatus = 2
	AccountStatus_SUSPENDED                  AccountStatus = 3
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "ACTIVE",
		3: "SUSPENDED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"PENDING":                    1,
		"ACTIVE":                     2,
		"SUSPENDED":                  3,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_identity_proto_enumTypes[1].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_auth_identity_proto_enumTypes[1]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{1}
}

type OnboardStatus int32

const (
	OnboardStatus_ONBOARD_STATUS_UNSPECIFIED OnboardStatus = 0
	OnboardStatus_NEW                        OnboardStatus = 1
	OnboardStatus_IN_PROGRESS                OnboardStatus = 2
	OnboardStatus_DONE                       OnboardStatus = 3
)

// Enum value maps for OnboardStatus.
var (
	OnboardStatus_name = map[int32]string{
		0: "ONBOARD_STATUS_UNSPECIFIED",
		1: "NEW",
		2: "IN_PROGRESS",
		3: "DONE",
	}
	OnboardStatus_value = map[string]int32{
		"ONBOARD_STATUS_UNSPECIFIED": 0,
		"NEW":                        1,
		"IN_PROGRESS":                2,
		"DONE":                       3,
	}
)

func (x OnboardStatus) Enum() *OnboardStatus {
	p := new(OnboardStatus)
	*p = x
	return p
}

func (x OnboardStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnboardStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_identity_proto_enumTypes[2].Descriptor()
}

func (OnboardStatus) Type() protoreflect.EnumType {
	return &file_auth_identity_proto_enumTypes[2]
}

func (x OnboardStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnboardStatus.Descriptor instead.
func (OnboardStatus) EnumDescriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{2}
}

// ─────────────────────────  ACCOUNT  ─────────────────────────
type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      AccountProvider        `protobuf:"varint,2,opt,name=provider,proto3,enum=rem.auth_identity.v1.AccountProvider" json:"provider,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Status        AccountStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=rem.auth_identity.v1.AccountStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_auth_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{0}
}

func (x *AccountResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountResponse) GetProvider() AccountProvider {
	if x != nil {
		return x.Provider
	}
	return AccountProvider_ACCOUNT_PROVIDER_UNSPECIFIED
}

func (x *AccountResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountResponse) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *AccountResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AccountResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AccountResponse) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

// ─────────────────────────  USER  ─────────────────────────
type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PersonId      string                 `protobuf:"bytes,3,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	OnboardStatus OnboardStatus          `protobuf:"varint,4,opt,name=onboard_status,json=onboardStatus,proto3,enum=rem.auth_identity.v1.OnboardStatus" json:"onboard_status,omitempty"`
	LastLogin     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	// Relación con Account
	Account       *AccountResponse `protobuf:"bytes,9,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_auth_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{1}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UserResponse) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *UserResponse) GetOnboardStatus() OnboardStatus {
	if x != nil {
		return x.OnboardStatus
	}
	return OnboardStatus_ONBOARD_STATUS_UNSPECIFIED
}

func (x *UserResponse) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *UserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserResponse) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *UserResponse) GetAccount() *AccountResponse {
	if x != nil {
		return x.Account
	}
	return nil
}

// Token validation
type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // JWT token to validate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_auth_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_auth_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTokenResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ValidateTokenResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ValidateTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// User operations
type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_auth_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailRequest) Reset() {
	*x = GetUserByEmailRequest{}
	mi := &file_auth_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailRequest) ProtoMessage() {}

func (x *GetUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`                                                      // required
	PersonId      string                 `protobuf:"bytes,2,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`                                                         // optional
	OnboardStatus OnboardStatus          `protobuf:"varint,3,opt,name=onboard_status,json=onboardStatus,proto3,enum=rem.auth_identity.v1.OnboardStatus" json:"onboard_status,omitempty"` // optional, defaults to NEW
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_auth_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateUserRequest) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *CreateUserRequest) GetOnboardStatus() OnboardStatus {
	if x != nil {
		return x.OnboardStatus
	}
	return OnboardStatus_ONBOARD_STATUS_UNSPECIFIED
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                               // required
	PersonId      string                 `protobuf:"bytes,2,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`                                                         // optional
	OnboardStatus OnboardStatus          `protobuf:"varint,3,opt,name=onboard_status,json=onboardStatus,proto3,enum=rem.auth_identity.v1.OnboardStatus" json:"onboard_status,omitempty"` // optional
	UpdatedBy     string                 `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`                                                      // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_auth_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *UpdateUserRequest) GetOnboardStatus() OnboardStatus {
	if x != nil {
		return x.OnboardStatus
	}
	return OnboardStatus_ONBOARD_STATUS_UNSPECIFIED
}

func (x *UpdateUserRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type DeactivateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // required
	UpdatedBy     string                 `protobuf:"bytes,2,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateUserRequest) Reset() {
	*x = DeactivateUserRequest{}
	mi := &file_auth_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateUserRequest) ProtoMessage() {}

func (x *DeactivateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateUserRequest.ProtoReflect.Descriptor instead.
func (*DeactivateUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{8}
}

func (x *DeactivateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeactivateUserRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

// Account operations
type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_auth_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{9}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UpdateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`                   // required
	Status        AccountStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=rem.auth_identity.v1.AccountStatus" json:"status,omitempty"` // optional
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`                   // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_auth_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_auth_identity_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateAccountRequest) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *UpdateAccountRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

var File_auth_identity_proto protoreflect.FileDescriptor

const file_auth_identity_proto_rawDesc = "" +
	"\n" +
	"\x13auth_identity.proto\x12\x14rem.auth_identity.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x02\n" +
	"\x0fAccountResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\bprovider\x18\x02 \x01(\x0e2%.rem.auth_identity.v1.AccountProviderR\bprovider\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.rem.auth_identity.v1.AccountStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\a \x01(\tR\tupdatedBy\"\xb7\x03\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1b\n" +
	"\tperson_id\x18\x03 \x01(\tR\bpersonId\x12J\n" +
	"\x0eonboard_status\x18\x04 \x01(\x0e2#.rem.auth_identity.v1.OnboardStatusR\ronboardStatus\x129\n" +
	"\n" +
	"last_login\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\x12?\n" +
	"\aaccount\x18\t \x01(\v2%.rem.auth_identity.v1.AccountResponseR\aaccount\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x94\x01\n" +
	"\x15ValidateTokenResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\"-\n" +
	"\x12GetUserByIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"-\n" +
	"\x15GetUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x9b\x01\n" +
	"\x11CreateUserRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tperson_id\x18\x02 \x01(\tR\bpersonId\x12J\n" +
	"\x0eonboard_status\x18\x03 \x01(\x0e2#.rem.auth_identity.v1.OnboardStatusR\ronboardStatus\"\xb4\x01\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tperson_id\x18\x02 \x01(\tR\bpersonId\x12J\n" +
	"\x0eonboard_status\x18\x03 \x01(\x0e2#.rem.auth_identity.v1.OnboardStatusR\ronboardStatus\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\tR\tupdatedBy\"O\n" +
	"\x15DeactivateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x02 \x01(\tR\tupdatedBy\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\x91\x01\n" +
	"\x14UpdateAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.rem.auth_identity.v1.AccountStatusR\x06status\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\tupdatedBy*J\n" +
	"\x0fAccountProvider\x12 \n" +
	"\x1cACCOUNT_PROVIDER_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05EMAIL\x10\x01\x12\n" +
	"\n" +
	"\x06GOOGLE\x10\x02*W\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\r\n" +
	"\tSUSPENDED\x10\x03*S\n" +
	"\rOnboardStatus\x12\x1e\n" +
	"\x1aONBOARD_STATUS_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03NEW\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\b\n" +
	"\x04DONE\x10\x032\x8e\x06\n" +
	"\x13AuthIdentityService\x12h\n" +
	"\rValidateToken\x12*.rem.auth_identity.v1.ValidateTokenRequest\x1a+.rem.auth_identity.v1.ValidateTokenResponse\x12[\n" +
	"\vGetUserById\x12(.rem.auth_identity.v1.GetUserByIdRequest\x1a\".rem.auth_identity.v1.UserResponse\x12a\n" +
	"\x0eGetUserByEmail\x12+.rem.auth_identity.v1.GetUserByEmailRequest\x1a\".rem.auth_identity.v1.UserResponse\x12Y\n" +
	"\n" +
	"CreateUser\x12'.rem.auth_identity.v1.CreateUserRequest\x1a\".rem.auth_identity.v1.UserResponse\x12Y\n" +
	"\n" +
	"UpdateUser\x12'.rem.auth_identity.v1.UpdateUserRequest\x1a\".rem.auth_identity.v1.UserResponse\x12U\n" +
	"\x0eDeactivateUser\x12+.rem.auth_identity.v1.DeactivateUserRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\n" +
	"GetAccount\x12'.rem.auth_identity.v1.GetAccountRequest\x1a%.rem.auth_identity.v1.AccountResponse\x12b\n" +
	"\rUpdateAccount\x12*.rem.auth_identity.v1.UpdateAccountRequest\x1a%.rem.auth_identity.v1.AccountResponseBBZ@github.com/rem-gestion/rem-common/protos/auth-identity/v1;authpbb\x06proto3"

var (
	file_auth_identity_proto_rawDescOnce sync.Once
	file_auth_identity_proto_rawDescData []byte
)

func file_auth_identity_proto_rawDescGZIP() []byte {
	file_auth_identity_proto_rawDescOnce.Do(func() {
		file_auth_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_identity_proto_rawDesc), len(file_auth_identity_proto_rawDesc)))
	})
	return file_auth_identity_proto_rawDescData
}

var file_auth_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_auth_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_auth_identity_proto_goTypes = []any{
	(AccountProvider)(0),          // 0: rem.auth_identity.v1.AccountProvider
	(AccountStatus)(0),            // 1: rem.auth_identity.v1.AccountStatus
	(OnboardStatus)(0),            // 2: rem.auth_identity.v1.OnboardStatus
	(*AccountResponse)(nil),       // 3: rem.auth_identity.v1.AccountResponse
	(*UserResponse)(nil),          // 4: rem.auth_identity.v1.UserResponse
	(*ValidateTokenRequest)(nil),  // 5: rem.auth_identity.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 6: rem.auth_identity.v1.ValidateTokenResponse
	(*GetUserByIdRequest)(nil),    // 7: rem.auth_identity.v1.GetUserByIdRequest
	(*GetUserByEmailRequest)(nil), // 8: rem.auth_identity.v1.GetUserByEmailRequest
	(*CreateUserRequest)(nil),     // 9: rem.auth_identity.v1.CreateUserRequest
	(*UpdateUserRequest)(nil),     // 10: rem.auth_identity.v1.UpdateUserRequest
	(*DeactivateUserRequest)(nil), // 11: rem.auth_identity.v1.DeactivateUserRequest
	(*GetAccountRequest)(nil),     // 12: rem.auth_identity.v1.GetAccountRequest
	(*UpdateAccountRequest)(nil),  // 13: rem.auth_identity.v1.UpdateAccountRequest
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_auth_identity_proto_depIdxs = []int32{
	0,  // 0: rem.auth_identity.v1.AccountResponse.provider:type_name -> rem.auth_identity.v1.AccountProvider
	1,  // 1: rem.auth_identity.v1.AccountResponse.status:type_name -> rem.auth_identity.v1.AccountStatus
	14, // 2: rem.auth_identity.v1.AccountResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: rem.auth_identity.v1.AccountResponse.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 4: rem.auth_identity.v1.UserResponse.onboard_status:type_name -> rem.auth_identity.v1.OnboardStatus
	14, // 5: rem.auth_identity.v1.UserResponse.last_login:type_name -> google.protobuf.Timestamp
	14, // 6: rem.auth_identity.v1.UserResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 7: rem.auth_identity.v1.UserResponse.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 8: rem.auth_identity.v1.UserResponse.account:type_name -> rem.auth_identity.v1.AccountResponse
	2,  // 9: rem.auth_identity.v1.CreateUserRequest.onboard_status:type_name -> rem.auth_identity.v1.OnboardStatus
	2,  // 10: rem.auth_identity.v1.UpdateUserRequest.onboard_status:type_name -> rem.auth_identity.v1.OnboardStatus
	1,  // 11: rem.auth_identity.v1.UpdateAccountRequest.status:type_name -> rem.auth_identity.v1.AccountStatus
	5,  // 12: rem.auth_identity.v1.AuthIdentityService.ValidateToken:input_type -> rem.auth_identity.v1.ValidateTokenRequest
	7,  // 13: rem.auth_identity.v1.AuthIdentityService.GetUserById:input_type -> rem.auth_identity.v1.GetUserByIdRequest
	8,  // 14: rem.auth_identity.v1.AuthIdentityService.GetUserByEmail:input_type -> rem.auth_identity.v1.GetUserByEmailRequest
	9,  // 15: rem.auth_identity.v1.AuthIdentityService.CreateUser:input_type -> rem.auth_identity.v1.CreateUserRequest
	10, // 16: rem.auth_identity.v1.AuthIdentityService.UpdateUser:input_type -> rem.auth_identity.v1.UpdateUserRequest
	11, // 17: rem.auth_identity.v1.AuthIdentityService.DeactivateUser:input_type -> rem.auth_identity.v1.DeactivateUserRequest
	12, // 18: rem.auth_identity.v1.AuthIdentityService.GetAccount:input_type -> rem.auth_identity.v1.GetAccountRequest
	13, // 19: rem.auth_identity.v1.AuthIdentityService.UpdateAccount:input_type -> rem.auth_identity.v1.UpdateAccountRequest
	6,  // 20: rem.auth_identity.v1.AuthIdentityService.ValidateToken:output_type -> rem.auth_identity.v1.ValidateTokenResponse
	4,  // 21: rem.auth_identity.v1.AuthIdentityService.GetUserById:output_type -> rem.auth_identity.v1.UserResponse
	4,  // 22: rem.auth_identity.v1.AuthIdentityService.GetUserByEmail:output_type -> rem.auth_identity.v1.UserResponse
	4,  // 23: rem.auth_identity.v1.AuthIdentityService.CreateUser:output_type -> rem.auth_identity.v1.UserResponse
	4,  // 24: rem.auth_identity.v1.AuthIdentityService.UpdateUser:output_type -> rem.auth_identity.v1.UserResponse
	15, // 25: rem.auth_identity.v1.AuthIdentityService.DeactivateUser:output_type -> google.protobuf.Empty
	3,  // 26: rem.auth_identity.v1.AuthIdentityService.GetAccount:output_type -> rem.auth_identity.v1.AccountResponse
	3,  // 27: rem.auth_identity.v1.AuthIdentityService.UpdateAccount:output_type -> rem.auth_identity.v1.AccountResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_auth_identity_proto_init() }
func file_auth_identity_proto_init() {
	if File_auth_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_identity_proto_rawDesc), len(file_auth_identity_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_identity_proto_goTypes,
		DependencyIndexes: file_auth_identity_proto_depIdxs,
		EnumInfos:         file_auth_identity_proto_enumTypes,
		MessageInfos:      file_auth_identity_proto_msgTypes,
	}.Build()
	File_auth_identity_proto = out.File
	file_auth_identity_proto_goTypes = nil
	file_auth_identity_proto_depIdxs = nil
}
