events {}

http {
    upstream api-gateway_backend {
        server api-gateway:8000;
    }

    upstream users-api_backend {
        server users-api:4001;
    }

    upstream courses-api_backend {
        server courses-api:4002;
    }

    upstream inscription-api_backend {
        server inscription-api:4003;
    }

    upstream search-api_backend {
        server search-api:4004;
    }

    server {
        listen 80;

        # Por defecto, redirige al api_gateway
        location / {
            proxy_pass http://api-gateway_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Para usuarios
        location /api_users/ {
            proxy_pass http://users-api_backend/;
        }

        # Para cursos
        location /api_courses/ {
             proxy_pass http://courses-api_backend/api_courses/;
        }

        # Para inscripciones
        location /api_inscriptions/ {
            proxy_pass http://inscription-api_backend/;
        }

        # Para búsqueda (search)
        location /api_search/ {
            proxy_pass http://search-api_backend/search/;
        }
    }
}

