version: "3.9"

services:
  # ───────────────────── address DB ─────────────────────
  postgres_address:
    image: postgres:16-alpine
    container_name: postgres_address
    restart: unless-stopped
    environment:
      POSTGRES_USER:     user
      POSTGRES_PASSWORD: supersecreta
      POSTGRES_DB:       remgestion_address
    ports:
      - "5432:5432"          # expone 5432 en tu máquina
    volumes:
      - pgdata_address:/var/lib/postgresql/data

  # ───────────────────── person DB ──────────────────────
  postgres_person:
    image: postgres:16-alpine
    container_name: postgres_person
    restart: unless-stopped
    environment:
      POSTGRES_USER:     user
      POSTGRES_PASSWORD: supersecreta
      POSTGRES_DB:       remgestion_person
    ports:
      - "5433:5432"          # 5433 en host  →  5432 dentro del contenedor
    volumes:
      - pgdata_person:/var/lib/postgresql/data

  # ───────────────────── auth-identity DB ───────────────
  postgres_auth:
    image: postgres:16-alpine
    container_name: postgres_auth
    restart: unless-stopped
    environment:
      POSTGRES_USER:     user
      POSTGRES_PASSWORD: supersecreta
      POSTGRES_DB:       remgestion_auth
    ports:
      - "5434:5432"          # 5434 en host  →  5432 dentro del contenedor
    volumes:
      - pgdata_auth:/var/lib/postgresql/data

volumes:
  pgdata_address:
  pgdata_person:
  pgdata_auth:
