// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: property.proto

package propertypb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─────────────────────────  ENUMS  ──────────────────────────
type AmenityCategory int32

const (
	AmenityCategory_AMENITY_CATEGORY_UNSPECIFIED AmenityCategory = 0
	AmenityCategory_GENERAL                      AmenityCategory = 1
	AmenityCategory_SERVICES                     AmenityCategory = 2
	AmenityCategory_ENVIRONMENTS                 AmenityCategory = 3
	AmenityCategory_SECURITY                     AmenityCategory = 4
	AmenityCategory_COMFORT                      AmenityCategory = 5
)

// Enum value maps for AmenityCategory.
var (
	AmenityCategory_name = map[int32]string{
		0: "AMENITY_CATEGORY_UNSPECIFIED",
		1: "GENERAL",
		2: "SERVICES",
		3: "ENVIRONMENTS",
		4: "SECURITY",
		5: "COMFORT",
	}
	AmenityCategory_value = map[string]int32{
		"AMENITY_CATEGORY_UNSPECIFIED": 0,
		"GENERAL":                      1,
		"SERVICES":                     2,
		"ENVIRONMENTS":                 3,
		"SECURITY":                     4,
		"COMFORT":                      5,
	}
)

func (x AmenityCategory) Enum() *AmenityCategory {
	p := new(AmenityCategory)
	*p = x
	return p
}

func (x AmenityCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AmenityCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_property_proto_enumTypes[0].Descriptor()
}

func (AmenityCategory) Type() protoreflect.EnumType {
	return &file_property_proto_enumTypes[0]
}

func (x AmenityCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AmenityCategory.Descriptor instead.
func (AmenityCategory) EnumDescriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{0}
}

// ─────────────────────  MESSAGES  ────────────────────
type Property struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerPersonId  string                 `protobuf:"bytes,2,opt,name=owner_person_id,json=ownerPersonId,proto3" json:"owner_person_id,omitempty"`
	AddressId      string                 `protobuf:"bytes,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	PropertyTypeId int32                  `protobuf:"varint,4,opt,name=property_type_id,json=propertyTypeId,proto3" json:"property_type_id,omitempty"`
	InternalCode   string                 `protobuf:"bytes,5,opt,name=internal_code,json=internalCode,proto3" json:"internal_code,omitempty"`
	YearBuilt      int32                  `protobuf:"varint,6,opt,name=year_built,json=yearBuilt,proto3" json:"year_built,omitempty"`
	Bedrooms       int32                  `protobuf:"varint,7,opt,name=bedrooms,proto3" json:"bedrooms,omitempty"`
	Bathrooms      float64                `protobuf:"fixed64,8,opt,name=bathrooms,proto3" json:"bathrooms,omitempty"`
	TotalAreaSqm   float64                `protobuf:"fixed64,9,opt,name=total_area_sqm,json=totalAreaSqm,proto3" json:"total_area_sqm,omitempty"`
	CoveredAreaSqm float64                `protobuf:"fixed64,10,opt,name=covered_area_sqm,json=coveredAreaSqm,proto3" json:"covered_area_sqm,omitempty"`
	Description    string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,14,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_property_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Property) GetOwnerPersonId() string {
	if x != nil {
		return x.OwnerPersonId
	}
	return ""
}

func (x *Property) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *Property) GetPropertyTypeId() int32 {
	if x != nil {
		return x.PropertyTypeId
	}
	return 0
}

func (x *Property) GetInternalCode() string {
	if x != nil {
		return x.InternalCode
	}
	return ""
}

func (x *Property) GetYearBuilt() int32 {
	if x != nil {
		return x.YearBuilt
	}
	return 0
}

func (x *Property) GetBedrooms() int32 {
	if x != nil {
		return x.Bedrooms
	}
	return 0
}

func (x *Property) GetBathrooms() float64 {
	if x != nil {
		return x.Bathrooms
	}
	return 0
}

func (x *Property) GetTotalAreaSqm() float64 {
	if x != nil {
		return x.TotalAreaSqm
	}
	return 0
}

func (x *Property) GetCoveredAreaSqm() float64 {
	if x != nil {
		return x.CoveredAreaSqm
	}
	return 0
}

func (x *Property) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Property) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Property) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Property) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type PropertyType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyType) Reset() {
	*x = PropertyType{}
	mi := &file_property_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyType) ProtoMessage() {}

func (x *PropertyType) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyType.ProtoReflect.Descriptor instead.
func (*PropertyType) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{1}
}

func (x *PropertyType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PropertyType) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PropertyType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PropertyType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PropertyType) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *PropertyType) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PropertyType) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Amenity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      AmenityCategory        `protobuf:"varint,3,opt,name=category,proto3,enum=property.v1.AmenityCategory" json:"category,omitempty"`
	IconUrl       string                 `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amenity) Reset() {
	*x = Amenity{}
	mi := &file_property_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amenity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amenity) ProtoMessage() {}

func (x *Amenity) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amenity.ProtoReflect.Descriptor instead.
func (*Amenity) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{2}
}

func (x *Amenity) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Amenity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Amenity) GetCategory() AmenityCategory {
	if x != nil {
		return x.Category
	}
	return AmenityCategory_AMENITY_CATEGORY_UNSPECIFIED
}

func (x *Amenity) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

type PropertyAmenity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	AmenityId     int32                  `protobuf:"varint,2,opt,name=amenity_id,json=amenityId,proto3" json:"amenity_id,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Amenity       *Amenity               `protobuf:"bytes,4,opt,name=amenity,proto3" json:"amenity,omitempty"` // populated amenity data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyAmenity) Reset() {
	*x = PropertyAmenity{}
	mi := &file_property_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyAmenity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyAmenity) ProtoMessage() {}

func (x *PropertyAmenity) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyAmenity.ProtoReflect.Descriptor instead.
func (*PropertyAmenity) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{3}
}

func (x *PropertyAmenity) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *PropertyAmenity) GetAmenityId() int32 {
	if x != nil {
		return x.AmenityId
	}
	return 0
}

func (x *PropertyAmenity) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *PropertyAmenity) GetAmenity() *Amenity {
	if x != nil {
		return x.Amenity
	}
	return nil
}

// Property requests
type GetPropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertyRequest) Reset() {
	*x = GetPropertyRequest{}
	mi := &file_property_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertyRequest) ProtoMessage() {}

func (x *GetPropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertyRequest.ProtoReflect.Descriptor instead.
func (*GetPropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{4}
}

func (x *GetPropertyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PropertyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Property      *Property              `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyResponse) Reset() {
	*x = PropertyResponse{}
	mi := &file_property_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyResponse) ProtoMessage() {}

func (x *PropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyResponse.ProtoReflect.Descriptor instead.
func (*PropertyResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{5}
}

func (x *PropertyResponse) GetProperty() *Property {
	if x != nil {
		return x.Property
	}
	return nil
}

type ListPropertiesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	OwnerPersonId  string                 `protobuf:"bytes,3,opt,name=owner_person_id,json=ownerPersonId,proto3" json:"owner_person_id,omitempty"`
	PropertyTypeId int32                  `protobuf:"varint,4,opt,name=property_type_id,json=propertyTypeId,proto3" json:"property_type_id,omitempty"`
	InternalCode   string                 `protobuf:"bytes,5,opt,name=internal_code,json=internalCode,proto3" json:"internal_code,omitempty"`
	YearBuilt      int32                  `protobuf:"varint,6,opt,name=year_built,json=yearBuilt,proto3" json:"year_built,omitempty"`
	Bedrooms       int32                  `protobuf:"varint,7,opt,name=bedrooms,proto3" json:"bedrooms,omitempty"`
	Bathrooms      float64                `protobuf:"fixed64,8,opt,name=bathrooms,proto3" json:"bathrooms,omitempty"`
	MinTotalArea   float64                `protobuf:"fixed64,9,opt,name=min_total_area,json=minTotalArea,proto3" json:"min_total_area,omitempty"`
	MaxTotalArea   float64                `protobuf:"fixed64,10,opt,name=max_total_area,json=maxTotalArea,proto3" json:"max_total_area,omitempty"`
	City           string                 `protobuf:"bytes,11,opt,name=city,proto3" json:"city,omitempty"`
	State          string                 `protobuf:"bytes,12,opt,name=state,proto3" json:"state,omitempty"`
	IncludeDeleted bool                   `protobuf:"varint,13,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPropertiesRequest) Reset() {
	*x = ListPropertiesRequest{}
	mi := &file_property_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertiesRequest) ProtoMessage() {}

func (x *ListPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertiesRequest.ProtoReflect.Descriptor instead.
func (*ListPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{6}
}

func (x *ListPropertiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPropertiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPropertiesRequest) GetOwnerPersonId() string {
	if x != nil {
		return x.OwnerPersonId
	}
	return ""
}

func (x *ListPropertiesRequest) GetPropertyTypeId() int32 {
	if x != nil {
		return x.PropertyTypeId
	}
	return 0
}

func (x *ListPropertiesRequest) GetInternalCode() string {
	if x != nil {
		return x.InternalCode
	}
	return ""
}

func (x *ListPropertiesRequest) GetYearBuilt() int32 {
	if x != nil {
		return x.YearBuilt
	}
	return 0
}

func (x *ListPropertiesRequest) GetBedrooms() int32 {
	if x != nil {
		return x.Bedrooms
	}
	return 0
}

func (x *ListPropertiesRequest) GetBathrooms() float64 {
	if x != nil {
		return x.Bathrooms
	}
	return 0
}

func (x *ListPropertiesRequest) GetMinTotalArea() float64 {
	if x != nil {
		return x.MinTotalArea
	}
	return 0
}

func (x *ListPropertiesRequest) GetMaxTotalArea() float64 {
	if x != nil {
		return x.MaxTotalArea
	}
	return 0
}

func (x *ListPropertiesRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListPropertiesRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ListPropertiesRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type ListPropertiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    []*Property            `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertiesResponse) Reset() {
	*x = ListPropertiesResponse{}
	mi := &file_property_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertiesResponse) ProtoMessage() {}

func (x *ListPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertiesResponse.ProtoReflect.Descriptor instead.
func (*ListPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{7}
}

func (x *ListPropertiesResponse) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ListPropertiesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPropertiesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPropertiesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CreatePropertyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerPersonId  string                 `protobuf:"bytes,1,opt,name=owner_person_id,json=ownerPersonId,proto3" json:"owner_person_id,omitempty"`
	AddressId      string                 `protobuf:"bytes,2,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	PropertyTypeId int32                  `protobuf:"varint,3,opt,name=property_type_id,json=propertyTypeId,proto3" json:"property_type_id,omitempty"`
	InternalCode   string                 `protobuf:"bytes,4,opt,name=internal_code,json=internalCode,proto3" json:"internal_code,omitempty"`
	YearBuilt      int32                  `protobuf:"varint,5,opt,name=year_built,json=yearBuilt,proto3" json:"year_built,omitempty"`
	Bedrooms       int32                  `protobuf:"varint,6,opt,name=bedrooms,proto3" json:"bedrooms,omitempty"`
	Bathrooms      float64                `protobuf:"fixed64,7,opt,name=bathrooms,proto3" json:"bathrooms,omitempty"`
	TotalAreaSqm   float64                `protobuf:"fixed64,8,opt,name=total_area_sqm,json=totalAreaSqm,proto3" json:"total_area_sqm,omitempty"`
	CoveredAreaSqm float64                `protobuf:"fixed64,9,opt,name=covered_area_sqm,json=coveredAreaSqm,proto3" json:"covered_area_sqm,omitempty"`
	Description    string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePropertyRequest) Reset() {
	*x = CreatePropertyRequest{}
	mi := &file_property_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePropertyRequest) ProtoMessage() {}

func (x *CreatePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePropertyRequest.ProtoReflect.Descriptor instead.
func (*CreatePropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePropertyRequest) GetOwnerPersonId() string {
	if x != nil {
		return x.OwnerPersonId
	}
	return ""
}

func (x *CreatePropertyRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *CreatePropertyRequest) GetPropertyTypeId() int32 {
	if x != nil {
		return x.PropertyTypeId
	}
	return 0
}

func (x *CreatePropertyRequest) GetInternalCode() string {
	if x != nil {
		return x.InternalCode
	}
	return ""
}

func (x *CreatePropertyRequest) GetYearBuilt() int32 {
	if x != nil {
		return x.YearBuilt
	}
	return 0
}

func (x *CreatePropertyRequest) GetBedrooms() int32 {
	if x != nil {
		return x.Bedrooms
	}
	return 0
}

func (x *CreatePropertyRequest) GetBathrooms() float64 {
	if x != nil {
		return x.Bathrooms
	}
	return 0
}

func (x *CreatePropertyRequest) GetTotalAreaSqm() float64 {
	if x != nil {
		return x.TotalAreaSqm
	}
	return 0
}

func (x *CreatePropertyRequest) GetCoveredAreaSqm() float64 {
	if x != nil {
		return x.CoveredAreaSqm
	}
	return 0
}

func (x *CreatePropertyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdatePropertyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerPersonId  string                 `protobuf:"bytes,2,opt,name=owner_person_id,json=ownerPersonId,proto3" json:"owner_person_id,omitempty"`
	AddressId      string                 `protobuf:"bytes,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	PropertyTypeId int32                  `protobuf:"varint,4,opt,name=property_type_id,json=propertyTypeId,proto3" json:"property_type_id,omitempty"`
	InternalCode   string                 `protobuf:"bytes,5,opt,name=internal_code,json=internalCode,proto3" json:"internal_code,omitempty"`
	YearBuilt      int32                  `protobuf:"varint,6,opt,name=year_built,json=yearBuilt,proto3" json:"year_built,omitempty"`
	Bedrooms       int32                  `protobuf:"varint,7,opt,name=bedrooms,proto3" json:"bedrooms,omitempty"`
	Bathrooms      float64                `protobuf:"fixed64,8,opt,name=bathrooms,proto3" json:"bathrooms,omitempty"`
	TotalAreaSqm   float64                `protobuf:"fixed64,9,opt,name=total_area_sqm,json=totalAreaSqm,proto3" json:"total_area_sqm,omitempty"`
	CoveredAreaSqm float64                `protobuf:"fixed64,10,opt,name=covered_area_sqm,json=coveredAreaSqm,proto3" json:"covered_area_sqm,omitempty"`
	Description    string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdatePropertyRequest) Reset() {
	*x = UpdatePropertyRequest{}
	mi := &file_property_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePropertyRequest) ProtoMessage() {}

func (x *UpdatePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePropertyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePropertyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePropertyRequest) GetOwnerPersonId() string {
	if x != nil {
		return x.OwnerPersonId
	}
	return ""
}

func (x *UpdatePropertyRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *UpdatePropertyRequest) GetPropertyTypeId() int32 {
	if x != nil {
		return x.PropertyTypeId
	}
	return 0
}

func (x *UpdatePropertyRequest) GetInternalCode() string {
	if x != nil {
		return x.InternalCode
	}
	return ""
}

func (x *UpdatePropertyRequest) GetYearBuilt() int32 {
	if x != nil {
		return x.YearBuilt
	}
	return 0
}

func (x *UpdatePropertyRequest) GetBedrooms() int32 {
	if x != nil {
		return x.Bedrooms
	}
	return 0
}

func (x *UpdatePropertyRequest) GetBathrooms() float64 {
	if x != nil {
		return x.Bathrooms
	}
	return 0
}

func (x *UpdatePropertyRequest) GetTotalAreaSqm() float64 {
	if x != nil {
		return x.TotalAreaSqm
	}
	return 0
}

func (x *UpdatePropertyRequest) GetCoveredAreaSqm() float64 {
	if x != nil {
		return x.CoveredAreaSqm
	}
	return 0
}

func (x *UpdatePropertyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeletePropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePropertyRequest) Reset() {
	*x = DeletePropertyRequest{}
	mi := &file_property_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePropertyRequest) ProtoMessage() {}

func (x *DeletePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePropertyRequest.ProtoReflect.Descriptor instead.
func (*DeletePropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePropertyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Property Type requests
type GetPropertyTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertyTypeRequest) Reset() {
	*x = GetPropertyTypeRequest{}
	mi := &file_property_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertyTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertyTypeRequest) ProtoMessage() {}

func (x *GetPropertyTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertyTypeRequest.ProtoReflect.Descriptor instead.
func (*GetPropertyTypeRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{11}
}

func (x *GetPropertyTypeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PropertyTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyType  *PropertyType          `protobuf:"bytes,1,opt,name=property_type,json=propertyType,proto3" json:"property_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyTypeResponse) Reset() {
	*x = PropertyTypeResponse{}
	mi := &file_property_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyTypeResponse) ProtoMessage() {}

func (x *PropertyTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyTypeResponse.ProtoReflect.Descriptor instead.
func (*PropertyTypeResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{12}
}

func (x *PropertyTypeResponse) GetPropertyType() *PropertyType {
	if x != nil {
		return x.PropertyType
	}
	return nil
}

type ListPropertyTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertyTypesRequest) Reset() {
	*x = ListPropertyTypesRequest{}
	mi := &file_property_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertyTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertyTypesRequest) ProtoMessage() {}

func (x *ListPropertyTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertyTypesRequest.ProtoReflect.Descriptor instead.
func (*ListPropertyTypesRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{13}
}

func (x *ListPropertyTypesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPropertyTypesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPropertyTypesRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ListPropertyTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyTypes []*PropertyType        `protobuf:"bytes,1,rep,name=property_types,json=propertyTypes,proto3" json:"property_types,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertyTypesResponse) Reset() {
	*x = ListPropertyTypesResponse{}
	mi := &file_property_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertyTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertyTypesResponse) ProtoMessage() {}

func (x *ListPropertyTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertyTypesResponse.ProtoReflect.Descriptor instead.
func (*ListPropertyTypesResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{14}
}

func (x *ListPropertyTypesResponse) GetPropertyTypes() []*PropertyType {
	if x != nil {
		return x.PropertyTypes
	}
	return nil
}

func (x *ListPropertyTypesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPropertyTypesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPropertyTypesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Property Amenity requests
type ListPropertyAmenitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertyAmenitiesRequest) Reset() {
	*x = ListPropertyAmenitiesRequest{}
	mi := &file_property_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertyAmenitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertyAmenitiesRequest) ProtoMessage() {}

func (x *ListPropertyAmenitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertyAmenitiesRequest.ProtoReflect.Descriptor instead.
func (*ListPropertyAmenitiesRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{15}
}

func (x *ListPropertyAmenitiesRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

type ListPropertyAmenitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amenities     []*PropertyAmenity     `protobuf:"bytes,1,rep,name=amenities,proto3" json:"amenities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertyAmenitiesResponse) Reset() {
	*x = ListPropertyAmenitiesResponse{}
	mi := &file_property_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertyAmenitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertyAmenitiesResponse) ProtoMessage() {}

func (x *ListPropertyAmenitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertyAmenitiesResponse.ProtoReflect.Descriptor instead.
func (*ListPropertyAmenitiesResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{16}
}

func (x *ListPropertyAmenitiesResponse) GetAmenities() []*PropertyAmenity {
	if x != nil {
		return x.Amenities
	}
	return nil
}

type AddPropertyAmenityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	AmenityId     int32                  `protobuf:"varint,2,opt,name=amenity_id,json=amenityId,proto3" json:"amenity_id,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPropertyAmenityRequest) Reset() {
	*x = AddPropertyAmenityRequest{}
	mi := &file_property_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPropertyAmenityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPropertyAmenityRequest) ProtoMessage() {}

func (x *AddPropertyAmenityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPropertyAmenityRequest.ProtoReflect.Descriptor instead.
func (*AddPropertyAmenityRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{17}
}

func (x *AddPropertyAmenityRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *AddPropertyAmenityRequest) GetAmenityId() int32 {
	if x != nil {
		return x.AmenityId
	}
	return 0
}

func (x *AddPropertyAmenityRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type RemovePropertyAmenityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	AmenityId     int32                  `protobuf:"varint,2,opt,name=amenity_id,json=amenityId,proto3" json:"amenity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePropertyAmenityRequest) Reset() {
	*x = RemovePropertyAmenityRequest{}
	mi := &file_property_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePropertyAmenityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePropertyAmenityRequest) ProtoMessage() {}

func (x *RemovePropertyAmenityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePropertyAmenityRequest.ProtoReflect.Descriptor instead.
func (*RemovePropertyAmenityRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{18}
}

func (x *RemovePropertyAmenityRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *RemovePropertyAmenityRequest) GetAmenityId() int32 {
	if x != nil {
		return x.AmenityId
	}
	return 0
}

var File_property_proto protoreflect.FileDescriptor

const file_property_proto_rawDesc = "" +
	"\n" +
	"\x0eproperty.proto\x12\vproperty.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x04\n" +
	"\bProperty\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fowner_person_id\x18\x02 \x01(\tR\rownerPersonId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\tR\taddressId\x12(\n" +
	"\x10property_type_id\x18\x04 \x01(\x05R\x0epropertyTypeId\x12#\n" +
	"\rinternal_code\x18\x05 \x01(\tR\finternalCode\x12\x1d\n" +
	"\n" +
	"year_built\x18\x06 \x01(\x05R\tyearBuilt\x12\x1a\n" +
	"\bbedrooms\x18\a \x01(\x05R\bbedrooms\x12\x1c\n" +
	"\tbathrooms\x18\b \x01(\x01R\tbathrooms\x12$\n" +
	"\x0etotal_area_sqm\x18\t \x01(\x01R\ftotalAreaSqm\x12(\n" +
	"\x10covered_area_sqm\x18\n" +
	" \x01(\x01R\x0ecoveredAreaSqm\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x0e \x01(\tR\tupdatedBy\"\xfb\x01\n" +
	"\fPropertyType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x82\x01\n" +
	"\aAmenity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\bcategory\x18\x03 \x01(\x0e2\x1c.property.v1.AmenityCategoryR\bcategory\x12\x19\n" +
	"\bicon_url\x18\x04 \x01(\tR\aiconUrl\"\x95\x01\n" +
	"\x0fPropertyAmenity\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\x12\x1d\n" +
	"\n" +
	"amenity_id\x18\x02 \x01(\x05R\tamenityId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12.\n" +
	"\aamenity\x18\x04 \x01(\v2\x14.property.v1.AmenityR\aamenity\"$\n" +
	"\x12GetPropertyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x10PropertyResponse\x121\n" +
	"\bproperty\x18\x01 \x01(\v2\x15.property.v1.PropertyR\bproperty\"\xb0\x03\n" +
	"\x15ListPropertiesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12&\n" +
	"\x0fowner_person_id\x18\x03 \x01(\tR\rownerPersonId\x12(\n" +
	"\x10property_type_id\x18\x04 \x01(\x05R\x0epropertyTypeId\x12#\n" +
	"\rinternal_code\x18\x05 \x01(\tR\finternalCode\x12\x1d\n" +
	"\n" +
	"year_built\x18\x06 \x01(\x05R\tyearBuilt\x12\x1a\n" +
	"\bbedrooms\x18\a \x01(\x05R\bbedrooms\x12\x1c\n" +
	"\tbathrooms\x18\b \x01(\x01R\tbathrooms\x12$\n" +
	"\x0emin_total_area\x18\t \x01(\x01R\fminTotalArea\x12$\n" +
	"\x0emax_total_area\x18\n" +
	" \x01(\x01R\fmaxTotalArea\x12\x12\n" +
	"\x04city\x18\v \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\f \x01(\tR\x05state\x12'\n" +
	"\x0finclude_deleted\x18\r \x01(\bR\x0eincludeDeleted\"\x8f\x01\n" +
	"\x16ListPropertiesResponse\x125\n" +
	"\n" +
	"properties\x18\x01 \x03(\v2\x15.property.v1.PropertyR\n" +
	"properties\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xf8\x02\n" +
	"\x15CreatePropertyRequest\x12&\n" +
	"\x0fowner_person_id\x18\x01 \x01(\tR\rownerPersonId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x02 \x01(\tR\taddressId\x12(\n" +
	"\x10property_type_id\x18\x03 \x01(\x05R\x0epropertyTypeId\x12#\n" +
	"\rinternal_code\x18\x04 \x01(\tR\finternalCode\x12\x1d\n" +
	"\n" +
	"year_built\x18\x05 \x01(\x05R\tyearBuilt\x12\x1a\n" +
	"\bbedrooms\x18\x06 \x01(\x05R\bbedrooms\x12\x1c\n" +
	"\tbathrooms\x18\a \x01(\x01R\tbathrooms\x12$\n" +
	"\x0etotal_area_sqm\x18\b \x01(\x01R\ftotalAreaSqm\x12(\n" +
	"\x10covered_area_sqm\x18\t \x01(\x01R\x0ecoveredAreaSqm\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\"\x88\x03\n" +
	"\x15UpdatePropertyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fowner_person_id\x18\x02 \x01(\tR\rownerPersonId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\tR\taddressId\x12(\n" +
	"\x10property_type_id\x18\x04 \x01(\x05R\x0epropertyTypeId\x12#\n" +
	"\rinternal_code\x18\x05 \x01(\tR\finternalCode\x12\x1d\n" +
	"\n" +
	"year_built\x18\x06 \x01(\x05R\tyearBuilt\x12\x1a\n" +
	"\bbedrooms\x18\a \x01(\x05R\bbedrooms\x12\x1c\n" +
	"\tbathrooms\x18\b \x01(\x01R\tbathrooms\x12$\n" +
	"\x0etotal_area_sqm\x18\t \x01(\x01R\ftotalAreaSqm\x12(\n" +
	"\x10covered_area_sqm\x18\n" +
	" \x01(\x01R\x0ecoveredAreaSqm\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\"'\n" +
	"\x15DeletePropertyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16GetPropertyTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"V\n" +
	"\x14PropertyTypeResponse\x12>\n" +
	"\rproperty_type\x18\x01 \x01(\v2\x19.property.v1.PropertyTypeR\fpropertyType\"a\n" +
	"\x18ListPropertyTypesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\"\x9d\x01\n" +
	"\x19ListPropertyTypesResponse\x12@\n" +
	"\x0eproperty_types\x18\x01 \x03(\v2\x19.property.v1.PropertyTypeR\rpropertyTypes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"?\n" +
	"\x1cListPropertyAmenitiesRequest\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\"[\n" +
	"\x1dListPropertyAmenitiesResponse\x12:\n" +
	"\tamenities\x18\x01 \x03(\v2\x1c.property.v1.PropertyAmenityR\tamenities\"o\n" +
	"\x19AddPropertyAmenityRequest\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\x12\x1d\n" +
	"\n" +
	"amenity_id\x18\x02 \x01(\x05R\tamenityId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"^\n" +
	"\x1cRemovePropertyAmenityRequest\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\x12\x1d\n" +
	"\n" +
	"amenity_id\x18\x02 \x01(\x05R\tamenityId*{\n" +
	"\x0fAmenityCategory\x12 \n" +
	"\x1cAMENITY_CATEGORY_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aGENERAL\x10\x01\x12\f\n" +
	"\bSERVICES\x10\x02\x12\x10\n" +
	"\fENVIRONMENTS\x10\x03\x12\f\n" +
	"\bSECURITY\x10\x04\x12\v\n" +
	"\aCOMFORT\x10\x052\x94\a\n" +
	"\x0fPropertyService\x12M\n" +
	"\vGetProperty\x12\x1f.property.v1.GetPropertyRequest\x1a\x1d.property.v1.PropertyResponse\x12Y\n" +
	"\x0eListProperties\x12\".property.v1.ListPropertiesRequest\x1a#.property.v1.ListPropertiesResponse\x12S\n" +
	"\x0eCreateProperty\x12\".property.v1.CreatePropertyRequest\x1a\x1d.property.v1.PropertyResponse\x12S\n" +
	"\x0eUpdateProperty\x12\".property.v1.UpdatePropertyRequest\x1a\x1d.property.v1.PropertyResponse\x12L\n" +
	"\x0eDeleteProperty\x12\".property.v1.DeletePropertyRequest\x1a\x16.google.protobuf.Empty\x12Y\n" +
	"\x0fGetPropertyType\x12#.property.v1.GetPropertyTypeRequest\x1a!.property.v1.PropertyTypeResponse\x12b\n" +
	"\x11ListPropertyTypes\x12%.property.v1.ListPropertyTypesRequest\x1a&.property.v1.ListPropertyTypesResponse\x12n\n" +
	"\x15ListPropertyAmenities\x12).property.v1.ListPropertyAmenitiesRequest\x1a*.property.v1.ListPropertyAmenitiesResponse\x12T\n" +
	"\x12AddPropertyAmenity\x12&.property.v1.AddPropertyAmenityRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\x15RemovePropertyAmenity\x12).property.v1.RemovePropertyAmenityRequest\x1a\x16.google.protobuf.EmptyBAZ?github.com/rem-gestion/rem-common/protos/property/v1;propertypbb\x06proto3"

var (
	file_property_proto_rawDescOnce sync.Once
	file_property_proto_rawDescData []byte
)

func file_property_proto_rawDescGZIP() []byte {
	file_property_proto_rawDescOnce.Do(func() {
		file_property_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_property_proto_rawDesc), len(file_property_proto_rawDesc)))
	})
	return file_property_proto_rawDescData
}

var file_property_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_property_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_property_proto_goTypes = []any{
	(AmenityCategory)(0),                  // 0: property.v1.AmenityCategory
	(*Property)(nil),                      // 1: property.v1.Property
	(*PropertyType)(nil),                  // 2: property.v1.PropertyType
	(*Amenity)(nil),                       // 3: property.v1.Amenity
	(*PropertyAmenity)(nil),               // 4: property.v1.PropertyAmenity
	(*GetPropertyRequest)(nil),            // 5: property.v1.GetPropertyRequest
	(*PropertyResponse)(nil),              // 6: property.v1.PropertyResponse
	(*ListPropertiesRequest)(nil),         // 7: property.v1.ListPropertiesRequest
	(*ListPropertiesResponse)(nil),        // 8: property.v1.ListPropertiesResponse
	(*CreatePropertyRequest)(nil),         // 9: property.v1.CreatePropertyRequest
	(*UpdatePropertyRequest)(nil),         // 10: property.v1.UpdatePropertyRequest
	(*DeletePropertyRequest)(nil),         // 11: property.v1.DeletePropertyRequest
	(*GetPropertyTypeRequest)(nil),        // 12: property.v1.GetPropertyTypeRequest
	(*PropertyTypeResponse)(nil),          // 13: property.v1.PropertyTypeResponse
	(*ListPropertyTypesRequest)(nil),      // 14: property.v1.ListPropertyTypesRequest
	(*ListPropertyTypesResponse)(nil),     // 15: property.v1.ListPropertyTypesResponse
	(*ListPropertyAmenitiesRequest)(nil),  // 16: property.v1.ListPropertyAmenitiesRequest
	(*ListPropertyAmenitiesResponse)(nil), // 17: property.v1.ListPropertyAmenitiesResponse
	(*AddPropertyAmenityRequest)(nil),     // 18: property.v1.AddPropertyAmenityRequest
	(*RemovePropertyAmenityRequest)(nil),  // 19: property.v1.RemovePropertyAmenityRequest
	(*timestamppb.Timestamp)(nil),         // 20: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 21: google.protobuf.Empty
}
var file_property_proto_depIdxs = []int32{
	20, // 0: property.v1.Property.created_at:type_name -> google.protobuf.Timestamp
	20, // 1: property.v1.Property.updated_at:type_name -> google.protobuf.Timestamp
	20, // 2: property.v1.PropertyType.created_at:type_name -> google.protobuf.Timestamp
	20, // 3: property.v1.PropertyType.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: property.v1.Amenity.category:type_name -> property.v1.AmenityCategory
	3,  // 5: property.v1.PropertyAmenity.amenity:type_name -> property.v1.Amenity
	1,  // 6: property.v1.PropertyResponse.property:type_name -> property.v1.Property
	1,  // 7: property.v1.ListPropertiesResponse.properties:type_name -> property.v1.Property
	2,  // 8: property.v1.PropertyTypeResponse.property_type:type_name -> property.v1.PropertyType
	2,  // 9: property.v1.ListPropertyTypesResponse.property_types:type_name -> property.v1.PropertyType
	4,  // 10: property.v1.ListPropertyAmenitiesResponse.amenities:type_name -> property.v1.PropertyAmenity
	5,  // 11: property.v1.PropertyService.GetProperty:input_type -> property.v1.GetPropertyRequest
	7,  // 12: property.v1.PropertyService.ListProperties:input_type -> property.v1.ListPropertiesRequest
	9,  // 13: property.v1.PropertyService.CreateProperty:input_type -> property.v1.CreatePropertyRequest
	10, // 14: property.v1.PropertyService.UpdateProperty:input_type -> property.v1.UpdatePropertyRequest
	11, // 15: property.v1.PropertyService.DeleteProperty:input_type -> property.v1.DeletePropertyRequest
	12, // 16: property.v1.PropertyService.GetPropertyType:input_type -> property.v1.GetPropertyTypeRequest
	14, // 17: property.v1.PropertyService.ListPropertyTypes:input_type -> property.v1.ListPropertyTypesRequest
	16, // 18: property.v1.PropertyService.ListPropertyAmenities:input_type -> property.v1.ListPropertyAmenitiesRequest
	18, // 19: property.v1.PropertyService.AddPropertyAmenity:input_type -> property.v1.AddPropertyAmenityRequest
	19, // 20: property.v1.PropertyService.RemovePropertyAmenity:input_type -> property.v1.RemovePropertyAmenityRequest
	6,  // 21: property.v1.PropertyService.GetProperty:output_type -> property.v1.PropertyResponse
	8,  // 22: property.v1.PropertyService.ListProperties:output_type -> property.v1.ListPropertiesResponse
	6,  // 23: property.v1.PropertyService.CreateProperty:output_type -> property.v1.PropertyResponse
	6,  // 24: property.v1.PropertyService.UpdateProperty:output_type -> property.v1.PropertyResponse
	21, // 25: property.v1.PropertyService.DeleteProperty:output_type -> google.protobuf.Empty
	13, // 26: property.v1.PropertyService.GetPropertyType:output_type -> property.v1.PropertyTypeResponse
	15, // 27: property.v1.PropertyService.ListPropertyTypes:output_type -> property.v1.ListPropertyTypesResponse
	17, // 28: property.v1.PropertyService.ListPropertyAmenities:output_type -> property.v1.ListPropertyAmenitiesResponse
	21, // 29: property.v1.PropertyService.AddPropertyAmenity:output_type -> google.protobuf.Empty
	21, // 30: property.v1.PropertyService.RemovePropertyAmenity:output_type -> google.protobuf.Empty
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_property_proto_init() }
func file_property_proto_init() {
	if File_property_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_property_proto_rawDesc), len(file_property_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_property_proto_goTypes,
		DependencyIndexes: file_property_proto_depIdxs,
		EnumInfos:         file_property_proto_enumTypes,
		MessageInfos:      file_property_proto_msgTypes,
	}.Build()
	File_property_proto = out.File
	file_property_proto_goTypes = nil
	file_property_proto_depIdxs = nil
}
