// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: property.proto

package propertypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PropertyService_GetProperty_FullMethodName           = "/property.v1.PropertyService/GetProperty"
	PropertyService_ListProperties_FullMethodName        = "/property.v1.PropertyService/ListProperties"
	PropertyService_CreateProperty_FullMethodName        = "/property.v1.PropertyService/CreateProperty"
	PropertyService_UpdateProperty_FullMethodName        = "/property.v1.PropertyService/UpdateProperty"
	PropertyService_DeleteProperty_FullMethodName        = "/property.v1.PropertyService/DeleteProperty"
	PropertyService_GetPropertyType_FullMethodName       = "/property.v1.PropertyService/GetPropertyType"
	PropertyService_ListPropertyTypes_FullMethodName     = "/property.v1.PropertyService/ListPropertyTypes"
	PropertyService_ListPropertyAmenities_FullMethodName = "/property.v1.PropertyService/ListPropertyAmenities"
	PropertyService_AddPropertyAmenity_FullMethodName    = "/property.v1.PropertyService/AddPropertyAmenity"
	PropertyService_RemovePropertyAmenity_FullMethodName = "/property.v1.PropertyService/RemovePropertyAmenity"
)

// PropertyServiceClient is the client API for PropertyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ───────────────────────  PROPERTY SERVICE  ───────────────────
type PropertyServiceClient interface {
	// Properties --------------------------------------------------
	GetProperty(ctx context.Context, in *GetPropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error)
	ListProperties(ctx context.Context, in *ListPropertiesRequest, opts ...grpc.CallOption) (*ListPropertiesResponse, error)
	CreateProperty(ctx context.Context, in *CreatePropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error)
	UpdateProperty(ctx context.Context, in *UpdatePropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error)
	DeleteProperty(ctx context.Context, in *DeletePropertyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Property Types ----------------------------------------------
	GetPropertyType(ctx context.Context, in *GetPropertyTypeRequest, opts ...grpc.CallOption) (*PropertyTypeResponse, error)
	ListPropertyTypes(ctx context.Context, in *ListPropertyTypesRequest, opts ...grpc.CallOption) (*ListPropertyTypesResponse, error)
	// Property Amenities ------------------------------------------
	ListPropertyAmenities(ctx context.Context, in *ListPropertyAmenitiesRequest, opts ...grpc.CallOption) (*ListPropertyAmenitiesResponse, error)
	AddPropertyAmenity(ctx context.Context, in *AddPropertyAmenityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemovePropertyAmenity(ctx context.Context, in *RemovePropertyAmenityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type propertyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyServiceClient(cc grpc.ClientConnInterface) PropertyServiceClient {
	return &propertyServiceClient{cc}
}

func (c *propertyServiceClient) GetProperty(ctx context.Context, in *GetPropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyResponse)
	err := c.cc.Invoke(ctx, PropertyService_GetProperty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) ListProperties(ctx context.Context, in *ListPropertiesRequest, opts ...grpc.CallOption) (*ListPropertiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPropertiesResponse)
	err := c.cc.Invoke(ctx, PropertyService_ListProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) CreateProperty(ctx context.Context, in *CreatePropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyResponse)
	err := c.cc.Invoke(ctx, PropertyService_CreateProperty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) UpdateProperty(ctx context.Context, in *UpdatePropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyResponse)
	err := c.cc.Invoke(ctx, PropertyService_UpdateProperty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) DeleteProperty(ctx context.Context, in *DeletePropertyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PropertyService_DeleteProperty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) GetPropertyType(ctx context.Context, in *GetPropertyTypeRequest, opts ...grpc.CallOption) (*PropertyTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyTypeResponse)
	err := c.cc.Invoke(ctx, PropertyService_GetPropertyType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) ListPropertyTypes(ctx context.Context, in *ListPropertyTypesRequest, opts ...grpc.CallOption) (*ListPropertyTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPropertyTypesResponse)
	err := c.cc.Invoke(ctx, PropertyService_ListPropertyTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) ListPropertyAmenities(ctx context.Context, in *ListPropertyAmenitiesRequest, opts ...grpc.CallOption) (*ListPropertyAmenitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPropertyAmenitiesResponse)
	err := c.cc.Invoke(ctx, PropertyService_ListPropertyAmenities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) AddPropertyAmenity(ctx context.Context, in *AddPropertyAmenityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PropertyService_AddPropertyAmenity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) RemovePropertyAmenity(ctx context.Context, in *RemovePropertyAmenityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PropertyService_RemovePropertyAmenity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertyServiceServer is the server API for PropertyService service.
// All implementations must embed UnimplementedPropertyServiceServer
// for forward compatibility.
//
// ───────────────────────  PROPERTY SERVICE  ───────────────────
type PropertyServiceServer interface {
	// Properties --------------------------------------------------
	GetProperty(context.Context, *GetPropertyRequest) (*PropertyResponse, error)
	ListProperties(context.Context, *ListPropertiesRequest) (*ListPropertiesResponse, error)
	CreateProperty(context.Context, *CreatePropertyRequest) (*PropertyResponse, error)
	UpdateProperty(context.Context, *UpdatePropertyRequest) (*PropertyResponse, error)
	DeleteProperty(context.Context, *DeletePropertyRequest) (*emptypb.Empty, error)
	// Property Types ----------------------------------------------
	GetPropertyType(context.Context, *GetPropertyTypeRequest) (*PropertyTypeResponse, error)
	ListPropertyTypes(context.Context, *ListPropertyTypesRequest) (*ListPropertyTypesResponse, error)
	// Property Amenities ------------------------------------------
	ListPropertyAmenities(context.Context, *ListPropertyAmenitiesRequest) (*ListPropertyAmenitiesResponse, error)
	AddPropertyAmenity(context.Context, *AddPropertyAmenityRequest) (*emptypb.Empty, error)
	RemovePropertyAmenity(context.Context, *RemovePropertyAmenityRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPropertyServiceServer()
}

// UnimplementedPropertyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPropertyServiceServer struct{}

func (UnimplementedPropertyServiceServer) GetProperty(context.Context, *GetPropertyRequest) (*PropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProperty not implemented")
}
func (UnimplementedPropertyServiceServer) ListProperties(context.Context, *ListPropertiesRequest) (*ListPropertiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProperties not implemented")
}
func (UnimplementedPropertyServiceServer) CreateProperty(context.Context, *CreatePropertyRequest) (*PropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProperty not implemented")
}
func (UnimplementedPropertyServiceServer) UpdateProperty(context.Context, *UpdatePropertyRequest) (*PropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProperty not implemented")
}
func (UnimplementedPropertyServiceServer) DeleteProperty(context.Context, *DeletePropertyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProperty not implemented")
}
func (UnimplementedPropertyServiceServer) GetPropertyType(context.Context, *GetPropertyTypeRequest) (*PropertyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPropertyType not implemented")
}
func (UnimplementedPropertyServiceServer) ListPropertyTypes(context.Context, *ListPropertyTypesRequest) (*ListPropertyTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPropertyTypes not implemented")
}
func (UnimplementedPropertyServiceServer) ListPropertyAmenities(context.Context, *ListPropertyAmenitiesRequest) (*ListPropertyAmenitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPropertyAmenities not implemented")
}
func (UnimplementedPropertyServiceServer) AddPropertyAmenity(context.Context, *AddPropertyAmenityRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPropertyAmenity not implemented")
}
func (UnimplementedPropertyServiceServer) RemovePropertyAmenity(context.Context, *RemovePropertyAmenityRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePropertyAmenity not implemented")
}
func (UnimplementedPropertyServiceServer) mustEmbedUnimplementedPropertyServiceServer() {}
func (UnimplementedPropertyServiceServer) testEmbeddedByValue()                         {}

// UnsafePropertyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertyServiceServer will
// result in compilation errors.
type UnsafePropertyServiceServer interface {
	mustEmbedUnimplementedPropertyServiceServer()
}

func RegisterPropertyServiceServer(s grpc.ServiceRegistrar, srv PropertyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPropertyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PropertyService_ServiceDesc, srv)
}

func _PropertyService_GetProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).GetProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_GetProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).GetProperty(ctx, req.(*GetPropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_ListProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).ListProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_ListProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).ListProperties(ctx, req.(*ListPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_CreateProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).CreateProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_CreateProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).CreateProperty(ctx, req.(*CreatePropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_UpdateProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).UpdateProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_UpdateProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).UpdateProperty(ctx, req.(*UpdatePropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_DeleteProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).DeleteProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_DeleteProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).DeleteProperty(ctx, req.(*DeletePropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_GetPropertyType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropertyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).GetPropertyType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_GetPropertyType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).GetPropertyType(ctx, req.(*GetPropertyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_ListPropertyTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPropertyTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).ListPropertyTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_ListPropertyTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).ListPropertyTypes(ctx, req.(*ListPropertyTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_ListPropertyAmenities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPropertyAmenitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).ListPropertyAmenities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_ListPropertyAmenities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).ListPropertyAmenities(ctx, req.(*ListPropertyAmenitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_AddPropertyAmenity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPropertyAmenityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).AddPropertyAmenity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_AddPropertyAmenity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).AddPropertyAmenity(ctx, req.(*AddPropertyAmenityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_RemovePropertyAmenity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePropertyAmenityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).RemovePropertyAmenity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_RemovePropertyAmenity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).RemovePropertyAmenity(ctx, req.(*RemovePropertyAmenityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PropertyService_ServiceDesc is the grpc.ServiceDesc for PropertyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropertyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "property.v1.PropertyService",
	HandlerType: (*PropertyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProperty",
			Handler:    _PropertyService_GetProperty_Handler,
		},
		{
			MethodName: "ListProperties",
			Handler:    _PropertyService_ListProperties_Handler,
		},
		{
			MethodName: "CreateProperty",
			Handler:    _PropertyService_CreateProperty_Handler,
		},
		{
			MethodName: "UpdateProperty",
			Handler:    _PropertyService_UpdateProperty_Handler,
		},
		{
			MethodName: "DeleteProperty",
			Handler:    _PropertyService_DeleteProperty_Handler,
		},
		{
			MethodName: "GetPropertyType",
			Handler:    _PropertyService_GetPropertyType_Handler,
		},
		{
			MethodName: "ListPropertyTypes",
			Handler:    _PropertyService_ListPropertyTypes_Handler,
		},
		{
			MethodName: "ListPropertyAmenities",
			Handler:    _PropertyService_ListPropertyAmenities_Handler,
		},
		{
			MethodName: "AddPropertyAmenity",
			Handler:    _PropertyService_AddPropertyAmenity_Handler,
		},
		{
			MethodName: "RemovePropertyAmenity",
			Handler:    _PropertyService_RemovePropertyAmenity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "property.proto",
}
