// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/property.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PropertyService_CreateProperty_FullMethodName   = "/property.PropertyService/CreateProperty"
	PropertyService_GetProperty_FullMethodName      = "/property.PropertyService/GetProperty"
	PropertyService_UpdateProperty_FullMethodName   = "/property.PropertyService/UpdateProperty"
	PropertyService_DeleteProperty_FullMethodName   = "/property.PropertyService/DeleteProperty"
	PropertyService_ListProperties_FullMethodName   = "/property.PropertyService/ListProperties"
	PropertyService_SearchProperties_FullMethodName = "/property.PropertyService/SearchProperties"
)

// PropertyServiceClient is the client API for PropertyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Property Service
type PropertyServiceClient interface {
	CreateProperty(ctx context.Context, in *CreatePropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error)
	GetProperty(ctx context.Context, in *GetPropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error)
	UpdateProperty(ctx context.Context, in *UpdatePropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error)
	DeleteProperty(ctx context.Context, in *DeletePropertyRequest, opts ...grpc.CallOption) (*DeletePropertyResponse, error)
	ListProperties(ctx context.Context, in *ListPropertiesRequest, opts ...grpc.CallOption) (*ListPropertiesResponse, error)
	SearchProperties(ctx context.Context, in *SearchPropertiesRequest, opts ...grpc.CallOption) (*ListPropertiesResponse, error)
}

type propertyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyServiceClient(cc grpc.ClientConnInterface) PropertyServiceClient {
	return &propertyServiceClient{cc}
}

func (c *propertyServiceClient) CreateProperty(ctx context.Context, in *CreatePropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyResponse)
	err := c.cc.Invoke(ctx, PropertyService_CreateProperty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) GetProperty(ctx context.Context, in *GetPropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyResponse)
	err := c.cc.Invoke(ctx, PropertyService_GetProperty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) UpdateProperty(ctx context.Context, in *UpdatePropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyResponse)
	err := c.cc.Invoke(ctx, PropertyService_UpdateProperty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) DeleteProperty(ctx context.Context, in *DeletePropertyRequest, opts ...grpc.CallOption) (*DeletePropertyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePropertyResponse)
	err := c.cc.Invoke(ctx, PropertyService_DeleteProperty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) ListProperties(ctx context.Context, in *ListPropertiesRequest, opts ...grpc.CallOption) (*ListPropertiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPropertiesResponse)
	err := c.cc.Invoke(ctx, PropertyService_ListProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) SearchProperties(ctx context.Context, in *SearchPropertiesRequest, opts ...grpc.CallOption) (*ListPropertiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPropertiesResponse)
	err := c.cc.Invoke(ctx, PropertyService_SearchProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertyServiceServer is the server API for PropertyService service.
// All implementations must embed UnimplementedPropertyServiceServer
// for forward compatibility.
//
// Property Service
type PropertyServiceServer interface {
	CreateProperty(context.Context, *CreatePropertyRequest) (*PropertyResponse, error)
	GetProperty(context.Context, *GetPropertyRequest) (*PropertyResponse, error)
	UpdateProperty(context.Context, *UpdatePropertyRequest) (*PropertyResponse, error)
	DeleteProperty(context.Context, *DeletePropertyRequest) (*DeletePropertyResponse, error)
	ListProperties(context.Context, *ListPropertiesRequest) (*ListPropertiesResponse, error)
	SearchProperties(context.Context, *SearchPropertiesRequest) (*ListPropertiesResponse, error)
	mustEmbedUnimplementedPropertyServiceServer()
}

// UnimplementedPropertyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPropertyServiceServer struct{}

func (UnimplementedPropertyServiceServer) CreateProperty(context.Context, *CreatePropertyRequest) (*PropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProperty not implemented")
}
func (UnimplementedPropertyServiceServer) GetProperty(context.Context, *GetPropertyRequest) (*PropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProperty not implemented")
}
func (UnimplementedPropertyServiceServer) UpdateProperty(context.Context, *UpdatePropertyRequest) (*PropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProperty not implemented")
}
func (UnimplementedPropertyServiceServer) DeleteProperty(context.Context, *DeletePropertyRequest) (*DeletePropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProperty not implemented")
}
func (UnimplementedPropertyServiceServer) ListProperties(context.Context, *ListPropertiesRequest) (*ListPropertiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProperties not implemented")
}
func (UnimplementedPropertyServiceServer) SearchProperties(context.Context, *SearchPropertiesRequest) (*ListPropertiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProperties not implemented")
}
func (UnimplementedPropertyServiceServer) mustEmbedUnimplementedPropertyServiceServer() {}
func (UnimplementedPropertyServiceServer) testEmbeddedByValue()                         {}

// UnsafePropertyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertyServiceServer will
// result in compilation errors.
type UnsafePropertyServiceServer interface {
	mustEmbedUnimplementedPropertyServiceServer()
}

func RegisterPropertyServiceServer(s grpc.ServiceRegistrar, srv PropertyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPropertyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PropertyService_ServiceDesc, srv)
}

func _PropertyService_CreateProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).CreateProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_CreateProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).CreateProperty(ctx, req.(*CreatePropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_GetProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).GetProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_GetProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).GetProperty(ctx, req.(*GetPropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_UpdateProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).UpdateProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_UpdateProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).UpdateProperty(ctx, req.(*UpdatePropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_DeleteProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).DeleteProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_DeleteProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).DeleteProperty(ctx, req.(*DeletePropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_ListProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).ListProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_ListProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).ListProperties(ctx, req.(*ListPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_SearchProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).SearchProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_SearchProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).SearchProperties(ctx, req.(*SearchPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PropertyService_ServiceDesc is the grpc.ServiceDesc for PropertyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropertyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "property.PropertyService",
	HandlerType: (*PropertyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProperty",
			Handler:    _PropertyService_CreateProperty_Handler,
		},
		{
			MethodName: "GetProperty",
			Handler:    _PropertyService_GetProperty_Handler,
		},
		{
			MethodName: "UpdateProperty",
			Handler:    _PropertyService_UpdateProperty_Handler,
		},
		{
			MethodName: "DeleteProperty",
			Handler:    _PropertyService_DeleteProperty_Handler,
		},
		{
			MethodName: "ListProperties",
			Handler:    _PropertyService_ListProperties_Handler,
		},
		{
			MethodName: "SearchProperties",
			Handler:    _PropertyService_SearchProperties_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/property.proto",
}

const (
	PropertyTypeService_CreatePropertyType_FullMethodName = "/property.PropertyTypeService/CreatePropertyType"
	PropertyTypeService_GetPropertyType_FullMethodName    = "/property.PropertyTypeService/GetPropertyType"
	PropertyTypeService_ListPropertyTypes_FullMethodName  = "/property.PropertyTypeService/ListPropertyTypes"
)

// PropertyTypeServiceClient is the client API for PropertyTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PropertyType Service
type PropertyTypeServiceClient interface {
	CreatePropertyType(ctx context.Context, in *CreatePropertyTypeRequest, opts ...grpc.CallOption) (*PropertyTypeResponse, error)
	GetPropertyType(ctx context.Context, in *GetPropertyTypeRequest, opts ...grpc.CallOption) (*PropertyTypeResponse, error)
	ListPropertyTypes(ctx context.Context, in *ListPropertyTypesRequest, opts ...grpc.CallOption) (*ListPropertyTypesResponse, error)
}

type propertyTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyTypeServiceClient(cc grpc.ClientConnInterface) PropertyTypeServiceClient {
	return &propertyTypeServiceClient{cc}
}

func (c *propertyTypeServiceClient) CreatePropertyType(ctx context.Context, in *CreatePropertyTypeRequest, opts ...grpc.CallOption) (*PropertyTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyTypeResponse)
	err := c.cc.Invoke(ctx, PropertyTypeService_CreatePropertyType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyTypeServiceClient) GetPropertyType(ctx context.Context, in *GetPropertyTypeRequest, opts ...grpc.CallOption) (*PropertyTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyTypeResponse)
	err := c.cc.Invoke(ctx, PropertyTypeService_GetPropertyType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyTypeServiceClient) ListPropertyTypes(ctx context.Context, in *ListPropertyTypesRequest, opts ...grpc.CallOption) (*ListPropertyTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPropertyTypesResponse)
	err := c.cc.Invoke(ctx, PropertyTypeService_ListPropertyTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertyTypeServiceServer is the server API for PropertyTypeService service.
// All implementations must embed UnimplementedPropertyTypeServiceServer
// for forward compatibility.
//
// PropertyType Service
type PropertyTypeServiceServer interface {
	CreatePropertyType(context.Context, *CreatePropertyTypeRequest) (*PropertyTypeResponse, error)
	GetPropertyType(context.Context, *GetPropertyTypeRequest) (*PropertyTypeResponse, error)
	ListPropertyTypes(context.Context, *ListPropertyTypesRequest) (*ListPropertyTypesResponse, error)
	mustEmbedUnimplementedPropertyTypeServiceServer()
}

// UnimplementedPropertyTypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPropertyTypeServiceServer struct{}

func (UnimplementedPropertyTypeServiceServer) CreatePropertyType(context.Context, *CreatePropertyTypeRequest) (*PropertyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePropertyType not implemented")
}
func (UnimplementedPropertyTypeServiceServer) GetPropertyType(context.Context, *GetPropertyTypeRequest) (*PropertyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPropertyType not implemented")
}
func (UnimplementedPropertyTypeServiceServer) ListPropertyTypes(context.Context, *ListPropertyTypesRequest) (*ListPropertyTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPropertyTypes not implemented")
}
func (UnimplementedPropertyTypeServiceServer) mustEmbedUnimplementedPropertyTypeServiceServer() {}
func (UnimplementedPropertyTypeServiceServer) testEmbeddedByValue()                             {}

// UnsafePropertyTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertyTypeServiceServer will
// result in compilation errors.
type UnsafePropertyTypeServiceServer interface {
	mustEmbedUnimplementedPropertyTypeServiceServer()
}

func RegisterPropertyTypeServiceServer(s grpc.ServiceRegistrar, srv PropertyTypeServiceServer) {
	// If the following call pancis, it indicates UnimplementedPropertyTypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PropertyTypeService_ServiceDesc, srv)
}

func _PropertyTypeService_CreatePropertyType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePropertyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyTypeServiceServer).CreatePropertyType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyTypeService_CreatePropertyType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyTypeServiceServer).CreatePropertyType(ctx, req.(*CreatePropertyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyTypeService_GetPropertyType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropertyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyTypeServiceServer).GetPropertyType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyTypeService_GetPropertyType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyTypeServiceServer).GetPropertyType(ctx, req.(*GetPropertyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyTypeService_ListPropertyTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPropertyTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyTypeServiceServer).ListPropertyTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyTypeService_ListPropertyTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyTypeServiceServer).ListPropertyTypes(ctx, req.(*ListPropertyTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PropertyTypeService_ServiceDesc is the grpc.ServiceDesc for PropertyTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropertyTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "property.PropertyTypeService",
	HandlerType: (*PropertyTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePropertyType",
			Handler:    _PropertyTypeService_CreatePropertyType_Handler,
		},
		{
			MethodName: "GetPropertyType",
			Handler:    _PropertyTypeService_GetPropertyType_Handler,
		},
		{
			MethodName: "ListPropertyTypes",
			Handler:    _PropertyTypeService_ListPropertyTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/property.proto",
}

const (
	PropertyManagementService_CreatePropertyManagement_FullMethodName = "/property.PropertyManagementService/CreatePropertyManagement"
	PropertyManagementService_GetPropertyManagement_FullMethodName    = "/property.PropertyManagementService/GetPropertyManagement"
	PropertyManagementService_ListPropertyManagements_FullMethodName  = "/property.PropertyManagementService/ListPropertyManagements"
)

// PropertyManagementServiceClient is the client API for PropertyManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PropertyManagement Service
type PropertyManagementServiceClient interface {
	CreatePropertyManagement(ctx context.Context, in *CreatePropertyManagementRequest, opts ...grpc.CallOption) (*PropertyManagementResponse, error)
	GetPropertyManagement(ctx context.Context, in *GetPropertyManagementRequest, opts ...grpc.CallOption) (*PropertyManagementResponse, error)
	ListPropertyManagements(ctx context.Context, in *ListPropertyManagementsRequest, opts ...grpc.CallOption) (*ListPropertyManagementsResponse, error)
}

type propertyManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyManagementServiceClient(cc grpc.ClientConnInterface) PropertyManagementServiceClient {
	return &propertyManagementServiceClient{cc}
}

func (c *propertyManagementServiceClient) CreatePropertyManagement(ctx context.Context, in *CreatePropertyManagementRequest, opts ...grpc.CallOption) (*PropertyManagementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyManagementResponse)
	err := c.cc.Invoke(ctx, PropertyManagementService_CreatePropertyManagement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyManagementServiceClient) GetPropertyManagement(ctx context.Context, in *GetPropertyManagementRequest, opts ...grpc.CallOption) (*PropertyManagementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyManagementResponse)
	err := c.cc.Invoke(ctx, PropertyManagementService_GetPropertyManagement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyManagementServiceClient) ListPropertyManagements(ctx context.Context, in *ListPropertyManagementsRequest, opts ...grpc.CallOption) (*ListPropertyManagementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPropertyManagementsResponse)
	err := c.cc.Invoke(ctx, PropertyManagementService_ListPropertyManagements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertyManagementServiceServer is the server API for PropertyManagementService service.
// All implementations must embed UnimplementedPropertyManagementServiceServer
// for forward compatibility.
//
// PropertyManagement Service
type PropertyManagementServiceServer interface {
	CreatePropertyManagement(context.Context, *CreatePropertyManagementRequest) (*PropertyManagementResponse, error)
	GetPropertyManagement(context.Context, *GetPropertyManagementRequest) (*PropertyManagementResponse, error)
	ListPropertyManagements(context.Context, *ListPropertyManagementsRequest) (*ListPropertyManagementsResponse, error)
	mustEmbedUnimplementedPropertyManagementServiceServer()
}

// UnimplementedPropertyManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPropertyManagementServiceServer struct{}

func (UnimplementedPropertyManagementServiceServer) CreatePropertyManagement(context.Context, *CreatePropertyManagementRequest) (*PropertyManagementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePropertyManagement not implemented")
}
func (UnimplementedPropertyManagementServiceServer) GetPropertyManagement(context.Context, *GetPropertyManagementRequest) (*PropertyManagementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPropertyManagement not implemented")
}
func (UnimplementedPropertyManagementServiceServer) ListPropertyManagements(context.Context, *ListPropertyManagementsRequest) (*ListPropertyManagementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPropertyManagements not implemented")
}
func (UnimplementedPropertyManagementServiceServer) mustEmbedUnimplementedPropertyManagementServiceServer() {
}
func (UnimplementedPropertyManagementServiceServer) testEmbeddedByValue() {}

// UnsafePropertyManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertyManagementServiceServer will
// result in compilation errors.
type UnsafePropertyManagementServiceServer interface {
	mustEmbedUnimplementedPropertyManagementServiceServer()
}

func RegisterPropertyManagementServiceServer(s grpc.ServiceRegistrar, srv PropertyManagementServiceServer) {
	// If the following call pancis, it indicates UnimplementedPropertyManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PropertyManagementService_ServiceDesc, srv)
}

func _PropertyManagementService_CreatePropertyManagement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePropertyManagementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyManagementServiceServer).CreatePropertyManagement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyManagementService_CreatePropertyManagement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyManagementServiceServer).CreatePropertyManagement(ctx, req.(*CreatePropertyManagementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyManagementService_GetPropertyManagement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropertyManagementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyManagementServiceServer).GetPropertyManagement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyManagementService_GetPropertyManagement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyManagementServiceServer).GetPropertyManagement(ctx, req.(*GetPropertyManagementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyManagementService_ListPropertyManagements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPropertyManagementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyManagementServiceServer).ListPropertyManagements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyManagementService_ListPropertyManagements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyManagementServiceServer).ListPropertyManagements(ctx, req.(*ListPropertyManagementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PropertyManagementService_ServiceDesc is the grpc.ServiceDesc for PropertyManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropertyManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "property.PropertyManagementService",
	HandlerType: (*PropertyManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePropertyManagement",
			Handler:    _PropertyManagementService_CreatePropertyManagement_Handler,
		},
		{
			MethodName: "GetPropertyManagement",
			Handler:    _PropertyManagementService_GetPropertyManagement_Handler,
		},
		{
			MethodName: "ListPropertyManagements",
			Handler:    _PropertyManagementService_ListPropertyManagements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/property.proto",
}

const (
	PropertyListingService_CreatePropertyListing_FullMethodName  = "/property.PropertyListingService/CreatePropertyListing"
	PropertyListingService_GetPropertyListing_FullMethodName     = "/property.PropertyListingService/GetPropertyListing"
	PropertyListingService_UpdatePropertyListing_FullMethodName  = "/property.PropertyListingService/UpdatePropertyListing"
	PropertyListingService_DeletePropertyListing_FullMethodName  = "/property.PropertyListingService/DeletePropertyListing"
	PropertyListingService_ListPropertyListings_FullMethodName   = "/property.PropertyListingService/ListPropertyListings"
	PropertyListingService_SearchPropertyListings_FullMethodName = "/property.PropertyListingService/SearchPropertyListings"
)

// PropertyListingServiceClient is the client API for PropertyListingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PropertyListing Service
type PropertyListingServiceClient interface {
	CreatePropertyListing(ctx context.Context, in *CreatePropertyListingRequest, opts ...grpc.CallOption) (*PropertyListingResponse, error)
	GetPropertyListing(ctx context.Context, in *GetPropertyListingRequest, opts ...grpc.CallOption) (*PropertyListingResponse, error)
	UpdatePropertyListing(ctx context.Context, in *UpdatePropertyListingRequest, opts ...grpc.CallOption) (*PropertyListingResponse, error)
	DeletePropertyListing(ctx context.Context, in *DeletePropertyListingRequest, opts ...grpc.CallOption) (*DeletePropertyListingResponse, error)
	ListPropertyListings(ctx context.Context, in *ListPropertyListingsRequest, opts ...grpc.CallOption) (*ListPropertyListingsResponse, error)
	SearchPropertyListings(ctx context.Context, in *SearchPropertyListingsRequest, opts ...grpc.CallOption) (*ListPropertyListingsResponse, error)
}

type propertyListingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyListingServiceClient(cc grpc.ClientConnInterface) PropertyListingServiceClient {
	return &propertyListingServiceClient{cc}
}

func (c *propertyListingServiceClient) CreatePropertyListing(ctx context.Context, in *CreatePropertyListingRequest, opts ...grpc.CallOption) (*PropertyListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyListingResponse)
	err := c.cc.Invoke(ctx, PropertyListingService_CreatePropertyListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyListingServiceClient) GetPropertyListing(ctx context.Context, in *GetPropertyListingRequest, opts ...grpc.CallOption) (*PropertyListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyListingResponse)
	err := c.cc.Invoke(ctx, PropertyListingService_GetPropertyListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyListingServiceClient) UpdatePropertyListing(ctx context.Context, in *UpdatePropertyListingRequest, opts ...grpc.CallOption) (*PropertyListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyListingResponse)
	err := c.cc.Invoke(ctx, PropertyListingService_UpdatePropertyListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyListingServiceClient) DeletePropertyListing(ctx context.Context, in *DeletePropertyListingRequest, opts ...grpc.CallOption) (*DeletePropertyListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePropertyListingResponse)
	err := c.cc.Invoke(ctx, PropertyListingService_DeletePropertyListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyListingServiceClient) ListPropertyListings(ctx context.Context, in *ListPropertyListingsRequest, opts ...grpc.CallOption) (*ListPropertyListingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPropertyListingsResponse)
	err := c.cc.Invoke(ctx, PropertyListingService_ListPropertyListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyListingServiceClient) SearchPropertyListings(ctx context.Context, in *SearchPropertyListingsRequest, opts ...grpc.CallOption) (*ListPropertyListingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPropertyListingsResponse)
	err := c.cc.Invoke(ctx, PropertyListingService_SearchPropertyListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertyListingServiceServer is the server API for PropertyListingService service.
// All implementations must embed UnimplementedPropertyListingServiceServer
// for forward compatibility.
//
// PropertyListing Service
type PropertyListingServiceServer interface {
	CreatePropertyListing(context.Context, *CreatePropertyListingRequest) (*PropertyListingResponse, error)
	GetPropertyListing(context.Context, *GetPropertyListingRequest) (*PropertyListingResponse, error)
	UpdatePropertyListing(context.Context, *UpdatePropertyListingRequest) (*PropertyListingResponse, error)
	DeletePropertyListing(context.Context, *DeletePropertyListingRequest) (*DeletePropertyListingResponse, error)
	ListPropertyListings(context.Context, *ListPropertyListingsRequest) (*ListPropertyListingsResponse, error)
	SearchPropertyListings(context.Context, *SearchPropertyListingsRequest) (*ListPropertyListingsResponse, error)
	mustEmbedUnimplementedPropertyListingServiceServer()
}

// UnimplementedPropertyListingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPropertyListingServiceServer struct{}

func (UnimplementedPropertyListingServiceServer) CreatePropertyListing(context.Context, *CreatePropertyListingRequest) (*PropertyListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePropertyListing not implemented")
}
func (UnimplementedPropertyListingServiceServer) GetPropertyListing(context.Context, *GetPropertyListingRequest) (*PropertyListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPropertyListing not implemented")
}
func (UnimplementedPropertyListingServiceServer) UpdatePropertyListing(context.Context, *UpdatePropertyListingRequest) (*PropertyListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePropertyListing not implemented")
}
func (UnimplementedPropertyListingServiceServer) DeletePropertyListing(context.Context, *DeletePropertyListingRequest) (*DeletePropertyListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePropertyListing not implemented")
}
func (UnimplementedPropertyListingServiceServer) ListPropertyListings(context.Context, *ListPropertyListingsRequest) (*ListPropertyListingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPropertyListings not implemented")
}
func (UnimplementedPropertyListingServiceServer) SearchPropertyListings(context.Context, *SearchPropertyListingsRequest) (*ListPropertyListingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPropertyListings not implemented")
}
func (UnimplementedPropertyListingServiceServer) mustEmbedUnimplementedPropertyListingServiceServer() {
}
func (UnimplementedPropertyListingServiceServer) testEmbeddedByValue() {}

// UnsafePropertyListingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertyListingServiceServer will
// result in compilation errors.
type UnsafePropertyListingServiceServer interface {
	mustEmbedUnimplementedPropertyListingServiceServer()
}

func RegisterPropertyListingServiceServer(s grpc.ServiceRegistrar, srv PropertyListingServiceServer) {
	// If the following call pancis, it indicates UnimplementedPropertyListingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PropertyListingService_ServiceDesc, srv)
}

func _PropertyListingService_CreatePropertyListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePropertyListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyListingServiceServer).CreatePropertyListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyListingService_CreatePropertyListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyListingServiceServer).CreatePropertyListing(ctx, req.(*CreatePropertyListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyListingService_GetPropertyListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropertyListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyListingServiceServer).GetPropertyListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyListingService_GetPropertyListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyListingServiceServer).GetPropertyListing(ctx, req.(*GetPropertyListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyListingService_UpdatePropertyListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePropertyListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyListingServiceServer).UpdatePropertyListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyListingService_UpdatePropertyListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyListingServiceServer).UpdatePropertyListing(ctx, req.(*UpdatePropertyListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyListingService_DeletePropertyListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePropertyListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyListingServiceServer).DeletePropertyListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyListingService_DeletePropertyListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyListingServiceServer).DeletePropertyListing(ctx, req.(*DeletePropertyListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyListingService_ListPropertyListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPropertyListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyListingServiceServer).ListPropertyListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyListingService_ListPropertyListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyListingServiceServer).ListPropertyListings(ctx, req.(*ListPropertyListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyListingService_SearchPropertyListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPropertyListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyListingServiceServer).SearchPropertyListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyListingService_SearchPropertyListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyListingServiceServer).SearchPropertyListings(ctx, req.(*SearchPropertyListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PropertyListingService_ServiceDesc is the grpc.ServiceDesc for PropertyListingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropertyListingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "property.PropertyListingService",
	HandlerType: (*PropertyListingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePropertyListing",
			Handler:    _PropertyListingService_CreatePropertyListing_Handler,
		},
		{
			MethodName: "GetPropertyListing",
			Handler:    _PropertyListingService_GetPropertyListing_Handler,
		},
		{
			MethodName: "UpdatePropertyListing",
			Handler:    _PropertyListingService_UpdatePropertyListing_Handler,
		},
		{
			MethodName: "DeletePropertyListing",
			Handler:    _PropertyListingService_DeletePropertyListing_Handler,
		},
		{
			MethodName: "ListPropertyListings",
			Handler:    _PropertyListingService_ListPropertyListings_Handler,
		},
		{
			MethodName: "SearchPropertyListings",
			Handler:    _PropertyListingService_SearchPropertyListings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/property.proto",
}

const (
	PropertyMediaService_CreatePropertyMedia_FullMethodName = "/property.PropertyMediaService/CreatePropertyMedia"
	PropertyMediaService_GetPropertyMedia_FullMethodName    = "/property.PropertyMediaService/GetPropertyMedia"
	PropertyMediaService_UpdatePropertyMedia_FullMethodName = "/property.PropertyMediaService/UpdatePropertyMedia"
	PropertyMediaService_DeletePropertyMedia_FullMethodName = "/property.PropertyMediaService/DeletePropertyMedia"
	PropertyMediaService_ListPropertyMedia_FullMethodName   = "/property.PropertyMediaService/ListPropertyMedia"
	PropertyMediaService_SetMainMedia_FullMethodName        = "/property.PropertyMediaService/SetMainMedia"
)

// PropertyMediaServiceClient is the client API for PropertyMediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PropertyMedia Service
type PropertyMediaServiceClient interface {
	CreatePropertyMedia(ctx context.Context, in *CreatePropertyMediaRequest, opts ...grpc.CallOption) (*PropertyMediaResponse, error)
	GetPropertyMedia(ctx context.Context, in *GetPropertyMediaRequest, opts ...grpc.CallOption) (*PropertyMediaResponse, error)
	UpdatePropertyMedia(ctx context.Context, in *UpdatePropertyMediaRequest, opts ...grpc.CallOption) (*PropertyMediaResponse, error)
	DeletePropertyMedia(ctx context.Context, in *DeletePropertyMediaRequest, opts ...grpc.CallOption) (*DeletePropertyMediaResponse, error)
	ListPropertyMedia(ctx context.Context, in *ListPropertyMediaRequest, opts ...grpc.CallOption) (*ListPropertyMediaResponse, error)
	SetMainMedia(ctx context.Context, in *SetMainMediaRequest, opts ...grpc.CallOption) (*PropertyMediaResponse, error)
}

type propertyMediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyMediaServiceClient(cc grpc.ClientConnInterface) PropertyMediaServiceClient {
	return &propertyMediaServiceClient{cc}
}

func (c *propertyMediaServiceClient) CreatePropertyMedia(ctx context.Context, in *CreatePropertyMediaRequest, opts ...grpc.CallOption) (*PropertyMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyMediaResponse)
	err := c.cc.Invoke(ctx, PropertyMediaService_CreatePropertyMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyMediaServiceClient) GetPropertyMedia(ctx context.Context, in *GetPropertyMediaRequest, opts ...grpc.CallOption) (*PropertyMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyMediaResponse)
	err := c.cc.Invoke(ctx, PropertyMediaService_GetPropertyMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyMediaServiceClient) UpdatePropertyMedia(ctx context.Context, in *UpdatePropertyMediaRequest, opts ...grpc.CallOption) (*PropertyMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyMediaResponse)
	err := c.cc.Invoke(ctx, PropertyMediaService_UpdatePropertyMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyMediaServiceClient) DeletePropertyMedia(ctx context.Context, in *DeletePropertyMediaRequest, opts ...grpc.CallOption) (*DeletePropertyMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePropertyMediaResponse)
	err := c.cc.Invoke(ctx, PropertyMediaService_DeletePropertyMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyMediaServiceClient) ListPropertyMedia(ctx context.Context, in *ListPropertyMediaRequest, opts ...grpc.CallOption) (*ListPropertyMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPropertyMediaResponse)
	err := c.cc.Invoke(ctx, PropertyMediaService_ListPropertyMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyMediaServiceClient) SetMainMedia(ctx context.Context, in *SetMainMediaRequest, opts ...grpc.CallOption) (*PropertyMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyMediaResponse)
	err := c.cc.Invoke(ctx, PropertyMediaService_SetMainMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertyMediaServiceServer is the server API for PropertyMediaService service.
// All implementations must embed UnimplementedPropertyMediaServiceServer
// for forward compatibility.
//
// PropertyMedia Service
type PropertyMediaServiceServer interface {
	CreatePropertyMedia(context.Context, *CreatePropertyMediaRequest) (*PropertyMediaResponse, error)
	GetPropertyMedia(context.Context, *GetPropertyMediaRequest) (*PropertyMediaResponse, error)
	UpdatePropertyMedia(context.Context, *UpdatePropertyMediaRequest) (*PropertyMediaResponse, error)
	DeletePropertyMedia(context.Context, *DeletePropertyMediaRequest) (*DeletePropertyMediaResponse, error)
	ListPropertyMedia(context.Context, *ListPropertyMediaRequest) (*ListPropertyMediaResponse, error)
	SetMainMedia(context.Context, *SetMainMediaRequest) (*PropertyMediaResponse, error)
	mustEmbedUnimplementedPropertyMediaServiceServer()
}

// UnimplementedPropertyMediaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPropertyMediaServiceServer struct{}

func (UnimplementedPropertyMediaServiceServer) CreatePropertyMedia(context.Context, *CreatePropertyMediaRequest) (*PropertyMediaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePropertyMedia not implemented")
}
func (UnimplementedPropertyMediaServiceServer) GetPropertyMedia(context.Context, *GetPropertyMediaRequest) (*PropertyMediaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPropertyMedia not implemented")
}
func (UnimplementedPropertyMediaServiceServer) UpdatePropertyMedia(context.Context, *UpdatePropertyMediaRequest) (*PropertyMediaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePropertyMedia not implemented")
}
func (UnimplementedPropertyMediaServiceServer) DeletePropertyMedia(context.Context, *DeletePropertyMediaRequest) (*DeletePropertyMediaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePropertyMedia not implemented")
}
func (UnimplementedPropertyMediaServiceServer) ListPropertyMedia(context.Context, *ListPropertyMediaRequest) (*ListPropertyMediaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPropertyMedia not implemented")
}
func (UnimplementedPropertyMediaServiceServer) SetMainMedia(context.Context, *SetMainMediaRequest) (*PropertyMediaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMainMedia not implemented")
}
func (UnimplementedPropertyMediaServiceServer) mustEmbedUnimplementedPropertyMediaServiceServer() {}
func (UnimplementedPropertyMediaServiceServer) testEmbeddedByValue()                              {}

// UnsafePropertyMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertyMediaServiceServer will
// result in compilation errors.
type UnsafePropertyMediaServiceServer interface {
	mustEmbedUnimplementedPropertyMediaServiceServer()
}

func RegisterPropertyMediaServiceServer(s grpc.ServiceRegistrar, srv PropertyMediaServiceServer) {
	// If the following call pancis, it indicates UnimplementedPropertyMediaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PropertyMediaService_ServiceDesc, srv)
}

func _PropertyMediaService_CreatePropertyMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePropertyMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyMediaServiceServer).CreatePropertyMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyMediaService_CreatePropertyMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyMediaServiceServer).CreatePropertyMedia(ctx, req.(*CreatePropertyMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyMediaService_GetPropertyMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropertyMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyMediaServiceServer).GetPropertyMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyMediaService_GetPropertyMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyMediaServiceServer).GetPropertyMedia(ctx, req.(*GetPropertyMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyMediaService_UpdatePropertyMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePropertyMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyMediaServiceServer).UpdatePropertyMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyMediaService_UpdatePropertyMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyMediaServiceServer).UpdatePropertyMedia(ctx, req.(*UpdatePropertyMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyMediaService_DeletePropertyMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePropertyMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyMediaServiceServer).DeletePropertyMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyMediaService_DeletePropertyMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyMediaServiceServer).DeletePropertyMedia(ctx, req.(*DeletePropertyMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyMediaService_ListPropertyMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPropertyMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyMediaServiceServer).ListPropertyMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyMediaService_ListPropertyMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyMediaServiceServer).ListPropertyMedia(ctx, req.(*ListPropertyMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyMediaService_SetMainMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMainMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyMediaServiceServer).SetMainMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyMediaService_SetMainMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyMediaServiceServer).SetMainMedia(ctx, req.(*SetMainMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PropertyMediaService_ServiceDesc is the grpc.ServiceDesc for PropertyMediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropertyMediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "property.PropertyMediaService",
	HandlerType: (*PropertyMediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePropertyMedia",
			Handler:    _PropertyMediaService_CreatePropertyMedia_Handler,
		},
		{
			MethodName: "GetPropertyMedia",
			Handler:    _PropertyMediaService_GetPropertyMedia_Handler,
		},
		{
			MethodName: "UpdatePropertyMedia",
			Handler:    _PropertyMediaService_UpdatePropertyMedia_Handler,
		},
		{
			MethodName: "DeletePropertyMedia",
			Handler:    _PropertyMediaService_DeletePropertyMedia_Handler,
		},
		{
			MethodName: "ListPropertyMedia",
			Handler:    _PropertyMediaService_ListPropertyMedia_Handler,
		},
		{
			MethodName: "SetMainMedia",
			Handler:    _PropertyMediaService_SetMainMedia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/property.proto",
}

const (
	PropertyValuationService_CreatePropertyValuation_FullMethodName = "/property.PropertyValuationService/CreatePropertyValuation"
	PropertyValuationService_GetPropertyValuation_FullMethodName    = "/property.PropertyValuationService/GetPropertyValuation"
	PropertyValuationService_UpdatePropertyValuation_FullMethodName = "/property.PropertyValuationService/UpdatePropertyValuation"
	PropertyValuationService_DeletePropertyValuation_FullMethodName = "/property.PropertyValuationService/DeletePropertyValuation"
	PropertyValuationService_ListPropertyValuations_FullMethodName  = "/property.PropertyValuationService/ListPropertyValuations"
	PropertyValuationService_GetLatestValuation_FullMethodName      = "/property.PropertyValuationService/GetLatestValuation"
)

// PropertyValuationServiceClient is the client API for PropertyValuationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PropertyValuation Service
type PropertyValuationServiceClient interface {
	CreatePropertyValuation(ctx context.Context, in *CreatePropertyValuationRequest, opts ...grpc.CallOption) (*PropertyValuationResponse, error)
	GetPropertyValuation(ctx context.Context, in *GetPropertyValuationRequest, opts ...grpc.CallOption) (*PropertyValuationResponse, error)
	UpdatePropertyValuation(ctx context.Context, in *UpdatePropertyValuationRequest, opts ...grpc.CallOption) (*PropertyValuationResponse, error)
	DeletePropertyValuation(ctx context.Context, in *DeletePropertyValuationRequest, opts ...grpc.CallOption) (*DeletePropertyValuationResponse, error)
	ListPropertyValuations(ctx context.Context, in *ListPropertyValuationsRequest, opts ...grpc.CallOption) (*ListPropertyValuationsResponse, error)
	GetLatestValuation(ctx context.Context, in *GetLatestValuationRequest, opts ...grpc.CallOption) (*PropertyValuationResponse, error)
}

type propertyValuationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyValuationServiceClient(cc grpc.ClientConnInterface) PropertyValuationServiceClient {
	return &propertyValuationServiceClient{cc}
}

func (c *propertyValuationServiceClient) CreatePropertyValuation(ctx context.Context, in *CreatePropertyValuationRequest, opts ...grpc.CallOption) (*PropertyValuationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyValuationResponse)
	err := c.cc.Invoke(ctx, PropertyValuationService_CreatePropertyValuation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyValuationServiceClient) GetPropertyValuation(ctx context.Context, in *GetPropertyValuationRequest, opts ...grpc.CallOption) (*PropertyValuationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyValuationResponse)
	err := c.cc.Invoke(ctx, PropertyValuationService_GetPropertyValuation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyValuationServiceClient) UpdatePropertyValuation(ctx context.Context, in *UpdatePropertyValuationRequest, opts ...grpc.CallOption) (*PropertyValuationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyValuationResponse)
	err := c.cc.Invoke(ctx, PropertyValuationService_UpdatePropertyValuation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyValuationServiceClient) DeletePropertyValuation(ctx context.Context, in *DeletePropertyValuationRequest, opts ...grpc.CallOption) (*DeletePropertyValuationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePropertyValuationResponse)
	err := c.cc.Invoke(ctx, PropertyValuationService_DeletePropertyValuation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyValuationServiceClient) ListPropertyValuations(ctx context.Context, in *ListPropertyValuationsRequest, opts ...grpc.CallOption) (*ListPropertyValuationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPropertyValuationsResponse)
	err := c.cc.Invoke(ctx, PropertyValuationService_ListPropertyValuations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyValuationServiceClient) GetLatestValuation(ctx context.Context, in *GetLatestValuationRequest, opts ...grpc.CallOption) (*PropertyValuationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyValuationResponse)
	err := c.cc.Invoke(ctx, PropertyValuationService_GetLatestValuation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertyValuationServiceServer is the server API for PropertyValuationService service.
// All implementations must embed UnimplementedPropertyValuationServiceServer
// for forward compatibility.
//
// PropertyValuation Service
type PropertyValuationServiceServer interface {
	CreatePropertyValuation(context.Context, *CreatePropertyValuationRequest) (*PropertyValuationResponse, error)
	GetPropertyValuation(context.Context, *GetPropertyValuationRequest) (*PropertyValuationResponse, error)
	UpdatePropertyValuation(context.Context, *UpdatePropertyValuationRequest) (*PropertyValuationResponse, error)
	DeletePropertyValuation(context.Context, *DeletePropertyValuationRequest) (*DeletePropertyValuationResponse, error)
	ListPropertyValuations(context.Context, *ListPropertyValuationsRequest) (*ListPropertyValuationsResponse, error)
	GetLatestValuation(context.Context, *GetLatestValuationRequest) (*PropertyValuationResponse, error)
	mustEmbedUnimplementedPropertyValuationServiceServer()
}

// UnimplementedPropertyValuationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPropertyValuationServiceServer struct{}

func (UnimplementedPropertyValuationServiceServer) CreatePropertyValuation(context.Context, *CreatePropertyValuationRequest) (*PropertyValuationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePropertyValuation not implemented")
}
func (UnimplementedPropertyValuationServiceServer) GetPropertyValuation(context.Context, *GetPropertyValuationRequest) (*PropertyValuationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPropertyValuation not implemented")
}
func (UnimplementedPropertyValuationServiceServer) UpdatePropertyValuation(context.Context, *UpdatePropertyValuationRequest) (*PropertyValuationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePropertyValuation not implemented")
}
func (UnimplementedPropertyValuationServiceServer) DeletePropertyValuation(context.Context, *DeletePropertyValuationRequest) (*DeletePropertyValuationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePropertyValuation not implemented")
}
func (UnimplementedPropertyValuationServiceServer) ListPropertyValuations(context.Context, *ListPropertyValuationsRequest) (*ListPropertyValuationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPropertyValuations not implemented")
}
func (UnimplementedPropertyValuationServiceServer) GetLatestValuation(context.Context, *GetLatestValuationRequest) (*PropertyValuationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestValuation not implemented")
}
func (UnimplementedPropertyValuationServiceServer) mustEmbedUnimplementedPropertyValuationServiceServer() {
}
func (UnimplementedPropertyValuationServiceServer) testEmbeddedByValue() {}

// UnsafePropertyValuationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertyValuationServiceServer will
// result in compilation errors.
type UnsafePropertyValuationServiceServer interface {
	mustEmbedUnimplementedPropertyValuationServiceServer()
}

func RegisterPropertyValuationServiceServer(s grpc.ServiceRegistrar, srv PropertyValuationServiceServer) {
	// If the following call pancis, it indicates UnimplementedPropertyValuationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PropertyValuationService_ServiceDesc, srv)
}

func _PropertyValuationService_CreatePropertyValuation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePropertyValuationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyValuationServiceServer).CreatePropertyValuation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyValuationService_CreatePropertyValuation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyValuationServiceServer).CreatePropertyValuation(ctx, req.(*CreatePropertyValuationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyValuationService_GetPropertyValuation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropertyValuationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyValuationServiceServer).GetPropertyValuation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyValuationService_GetPropertyValuation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyValuationServiceServer).GetPropertyValuation(ctx, req.(*GetPropertyValuationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyValuationService_UpdatePropertyValuation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePropertyValuationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyValuationServiceServer).UpdatePropertyValuation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyValuationService_UpdatePropertyValuation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyValuationServiceServer).UpdatePropertyValuation(ctx, req.(*UpdatePropertyValuationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyValuationService_DeletePropertyValuation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePropertyValuationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyValuationServiceServer).DeletePropertyValuation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyValuationService_DeletePropertyValuation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyValuationServiceServer).DeletePropertyValuation(ctx, req.(*DeletePropertyValuationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyValuationService_ListPropertyValuations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPropertyValuationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyValuationServiceServer).ListPropertyValuations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyValuationService_ListPropertyValuations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyValuationServiceServer).ListPropertyValuations(ctx, req.(*ListPropertyValuationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyValuationService_GetLatestValuation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestValuationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyValuationServiceServer).GetLatestValuation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyValuationService_GetLatestValuation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyValuationServiceServer).GetLatestValuation(ctx, req.(*GetLatestValuationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PropertyValuationService_ServiceDesc is the grpc.ServiceDesc for PropertyValuationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropertyValuationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "property.PropertyValuationService",
	HandlerType: (*PropertyValuationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePropertyValuation",
			Handler:    _PropertyValuationService_CreatePropertyValuation_Handler,
		},
		{
			MethodName: "GetPropertyValuation",
			Handler:    _PropertyValuationService_GetPropertyValuation_Handler,
		},
		{
			MethodName: "UpdatePropertyValuation",
			Handler:    _PropertyValuationService_UpdatePropertyValuation_Handler,
		},
		{
			MethodName: "DeletePropertyValuation",
			Handler:    _PropertyValuationService_DeletePropertyValuation_Handler,
		},
		{
			MethodName: "ListPropertyValuations",
			Handler:    _PropertyValuationService_ListPropertyValuations_Handler,
		},
		{
			MethodName: "GetLatestValuation",
			Handler:    _PropertyValuationService_GetLatestValuation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/property.proto",
}
