// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: person.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─────────────────────────  ENUMS  ──────────────────────────
type PersonType int32

const (
	PersonType_PERSON_TYPE_UNSPECIFIED PersonType = 0
	PersonType_INDIVIDUAL              PersonType = 1
	PersonType_COMPANY                 PersonType = 2
)

// Enum value maps for PersonType.
var (
	PersonType_name = map[int32]string{
		0: "PERSON_TYPE_UNSPECIFIED",
		1: "INDIVIDUAL",
		2: "COMPANY",
	}
	PersonType_value = map[string]int32{
		"PERSON_TYPE_UNSPECIFIED": 0,
		"INDIVIDUAL":              1,
		"COMPANY":                 2,
	}
)

func (x PersonType) Enum() *PersonType {
	p := new(PersonType)
	*p = x
	return p
}

func (x PersonType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersonType) Descriptor() protoreflect.EnumDescriptor {
	return file_person_proto_enumTypes[0].Descriptor()
}

func (PersonType) Type() protoreflect.EnumType {
	return &file_person_proto_enumTypes[0]
}

func (x PersonType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersonType.Descriptor instead.
func (PersonType) EnumDescriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{0}
}

type Sexo int32

const (
	Sexo_SEXO_UNSPECIFIED Sexo = 0
	Sexo_MASCULINO        Sexo = 1
	Sexo_FEMENINO         Sexo = 2
)

// Enum value maps for Sexo.
var (
	Sexo_name = map[int32]string{
		0: "SEXO_UNSPECIFIED",
		1: "MASCULINO",
		2: "FEMENINO",
	}
	Sexo_value = map[string]int32{
		"SEXO_UNSPECIFIED": 0,
		"MASCULINO":        1,
		"FEMENINO":         2,
	}
)

func (x Sexo) Enum() *Sexo {
	p := new(Sexo)
	*p = x
	return p
}

func (x Sexo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sexo) Descriptor() protoreflect.EnumDescriptor {
	return file_person_proto_enumTypes[1].Descriptor()
}

func (Sexo) Type() protoreflect.EnumType {
	return &file_person_proto_enumTypes[1]
}

func (x Sexo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sexo.Descriptor instead.
func (Sexo) EnumDescriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{1}
}

type ContactType int32

const (
	ContactType_CONTACT_TYPE_UNSPECIFIED ContactType = 0
	ContactType_EMAIL                    ContactType = 1
	ContactType_PHONE                    ContactType = 2
	ContactType_WHATSAPP                 ContactType = 3
)

// Enum value maps for ContactType.
var (
	ContactType_name = map[int32]string{
		0: "CONTACT_TYPE_UNSPECIFIED",
		1: "EMAIL",
		2: "PHONE",
		3: "WHATSAPP",
	}
	ContactType_value = map[string]int32{
		"CONTACT_TYPE_UNSPECIFIED": 0,
		"EMAIL":                    1,
		"PHONE":                    2,
		"WHATSAPP":                 3,
	}
)

func (x ContactType) Enum() *ContactType {
	p := new(ContactType)
	*p = x
	return p
}

func (x ContactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContactType) Descriptor() protoreflect.EnumDescriptor {
	return file_person_proto_enumTypes[2].Descriptor()
}

func (ContactType) Type() protoreflect.EnumType {
	return &file_person_proto_enumTypes[2]
}

func (x ContactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContactType.Descriptor instead.
func (ContactType) EnumDescriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{2}
}

// ─────────────────────────  PERSON  ─────────────────────────
type PersonResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type      PersonType             `protobuf:"varint,2,opt,name=type,proto3,enum=rem.person.v1.PersonType" json:"type,omitempty"`
	AddressId string                 `protobuf:"bytes,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"` // puede ser vacío
	AvatarUrl string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // puede ser vacío
	Sexo      Sexo                   `protobuf:"varint,5,opt,name=sexo,proto3,enum=rem.person.v1.Sexo" json:"sexo,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*PersonResponse_Individual
	//	*PersonResponse_Company
	Details       isPersonResponse_Details `protobuf_oneof:"details"`
	Contacts      []*Contact               `protobuf:"bytes,10,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonResponse) Reset() {
	*x = PersonResponse{}
	mi := &file_person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonResponse) ProtoMessage() {}

func (x *PersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonResponse.ProtoReflect.Descriptor instead.
func (*PersonResponse) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{0}
}

func (x *PersonResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PersonResponse) GetType() PersonType {
	if x != nil {
		return x.Type
	}
	return PersonType_PERSON_TYPE_UNSPECIFIED
}

func (x *PersonResponse) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *PersonResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *PersonResponse) GetSexo() Sexo {
	if x != nil {
		return x.Sexo
	}
	return Sexo_SEXO_UNSPECIFIED
}

func (x *PersonResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PersonResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PersonResponse) GetDetails() isPersonResponse_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *PersonResponse) GetIndividual() *Individual {
	if x != nil {
		if x, ok := x.Details.(*PersonResponse_Individual); ok {
			return x.Individual
		}
	}
	return nil
}

func (x *PersonResponse) GetCompany() *Company {
	if x != nil {
		if x, ok := x.Details.(*PersonResponse_Company); ok {
			return x.Company
		}
	}
	return nil
}

func (x *PersonResponse) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type isPersonResponse_Details interface {
	isPersonResponse_Details()
}

type PersonResponse_Individual struct {
	Individual *Individual `protobuf:"bytes,8,opt,name=individual,proto3,oneof"`
}

type PersonResponse_Company struct {
	Company *Company `protobuf:"bytes,9,opt,name=company,proto3,oneof"`
}

func (*PersonResponse_Individual) isPersonResponse_Details() {}

func (*PersonResponse_Company) isPersonResponse_Details() {}

type Individual struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Dni           string                 `protobuf:"bytes,3,opt,name=dni,proto3" json:"dni,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Individual) Reset() {
	*x = Individual{}
	mi := &file_person_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Individual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Individual) ProtoMessage() {}

func (x *Individual) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Individual.ProtoReflect.Descriptor instead.
func (*Individual) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{1}
}

func (x *Individual) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Individual) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Individual) GetDni() string {
	if x != nil {
		return x.Dni
	}
	return ""
}

type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LegalName     string                 `protobuf:"bytes,1,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	Cuit          string                 `protobuf:"bytes,2,opt,name=cuit,proto3" json:"cuit,omitempty"`
	SocietyType   string                 `protobuf:"bytes,3,opt,name=society_type,json=societyType,proto3" json:"society_type,omitempty"` // SA | SRL | SAS | …
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_person_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{2}
}

func (x *Company) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *Company) GetCuit() string {
	if x != nil {
		return x.Cuit
	}
	return ""
}

func (x *Company) GetSocietyType() string {
	if x != nil {
		return x.SocietyType
	}
	return ""
}

// ─────────────────────  CONTACT EMBED  ──────────────────────
type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo          ContactType            `protobuf:"varint,2,opt,name=tipo,proto3,enum=rem.person.v1.ContactType" json:"tipo,omitempty"`
	Dato          string                 `protobuf:"bytes,3,opt,name=dato,proto3" json:"dato,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_person_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{3}
}

func (x *Contact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contact) GetTipo() ContactType {
	if x != nil {
		return x.Tipo
	}
	return ContactType_CONTACT_TYPE_UNSPECIFIED
}

func (x *Contact) GetDato() string {
	if x != nil {
		return x.Dato
	}
	return ""
}

func (x *Contact) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *Contact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Personas
type CreatePersonRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      PersonType             `protobuf:"varint,1,opt,name=type,proto3,enum=rem.person.v1.PersonType" json:"type,omitempty"` // required
	AddressId string                 `protobuf:"bytes,2,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	AvatarUrl string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Sexo      Sexo                   `protobuf:"varint,4,opt,name=sexo,proto3,enum=rem.person.v1.Sexo" json:"sexo,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*CreatePersonRequest_Individual
	//	*CreatePersonRequest_Company
	Details       isCreatePersonRequest_Details `protobuf_oneof:"details"`
	Contacts      []*AddContactPayload          `protobuf:"bytes,7,rep,name=contacts,proto3" json:"contacts,omitempty"` // opcional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonRequest) Reset() {
	*x = CreatePersonRequest{}
	mi := &file_person_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonRequest) ProtoMessage() {}

func (x *CreatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePersonRequest) GetType() PersonType {
	if x != nil {
		return x.Type
	}
	return PersonType_PERSON_TYPE_UNSPECIFIED
}

func (x *CreatePersonRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *CreatePersonRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *CreatePersonRequest) GetSexo() Sexo {
	if x != nil {
		return x.Sexo
	}
	return Sexo_SEXO_UNSPECIFIED
}

func (x *CreatePersonRequest) GetDetails() isCreatePersonRequest_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *CreatePersonRequest) GetIndividual() *CreateIndividual {
	if x != nil {
		if x, ok := x.Details.(*CreatePersonRequest_Individual); ok {
			return x.Individual
		}
	}
	return nil
}

func (x *CreatePersonRequest) GetCompany() *CreateCompany {
	if x != nil {
		if x, ok := x.Details.(*CreatePersonRequest_Company); ok {
			return x.Company
		}
	}
	return nil
}

func (x *CreatePersonRequest) GetContacts() []*AddContactPayload {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type isCreatePersonRequest_Details interface {
	isCreatePersonRequest_Details()
}

type CreatePersonRequest_Individual struct {
	Individual *CreateIndividual `protobuf:"bytes,5,opt,name=individual,proto3,oneof"`
}

type CreatePersonRequest_Company struct {
	Company *CreateCompany `protobuf:"bytes,6,opt,name=company,proto3,oneof"`
}

func (*CreatePersonRequest_Individual) isCreatePersonRequest_Details() {}

func (*CreatePersonRequest_Company) isCreatePersonRequest_Details() {}

type UpdatePersonRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // required
	AddressId string                 `protobuf:"bytes,2,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	AvatarUrl string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Sexo      Sexo                   `protobuf:"varint,4,opt,name=sexo,proto3,enum=rem.person.v1.Sexo" json:"sexo,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*UpdatePersonRequest_Individual
	//	*UpdatePersonRequest_Company
	Details       isUpdatePersonRequest_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePersonRequest) Reset() {
	*x = UpdatePersonRequest{}
	mi := &file_person_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonRequest) ProtoMessage() {}

func (x *UpdatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonRequest.ProtoReflect.Descriptor instead.
func (*UpdatePersonRequest) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePersonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePersonRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *UpdatePersonRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdatePersonRequest) GetSexo() Sexo {
	if x != nil {
		return x.Sexo
	}
	return Sexo_SEXO_UNSPECIFIED
}

func (x *UpdatePersonRequest) GetDetails() isUpdatePersonRequest_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *UpdatePersonRequest) GetIndividual() *UpdateIndividual {
	if x != nil {
		if x, ok := x.Details.(*UpdatePersonRequest_Individual); ok {
			return x.Individual
		}
	}
	return nil
}

func (x *UpdatePersonRequest) GetCompany() *UpdateCompany {
	if x != nil {
		if x, ok := x.Details.(*UpdatePersonRequest_Company); ok {
			return x.Company
		}
	}
	return nil
}

type isUpdatePersonRequest_Details interface {
	isUpdatePersonRequest_Details()
}

type UpdatePersonRequest_Individual struct {
	Individual *UpdateIndividual `protobuf:"bytes,5,opt,name=individual,proto3,oneof"`
}

type UpdatePersonRequest_Company struct {
	Company *UpdateCompany `protobuf:"bytes,6,opt,name=company,proto3,oneof"`
}

func (*UpdatePersonRequest_Individual) isUpdatePersonRequest_Details() {}

func (*UpdatePersonRequest_Company) isUpdatePersonRequest_Details() {}

type GetPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonRequest) Reset() {
	*x = GetPersonRequest{}
	mi := &file_person_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonRequest) ProtoMessage() {}

func (x *GetPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonRequest.ProtoReflect.Descriptor instead.
func (*GetPersonRequest) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{6}
}

func (x *GetPersonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonRequest) Reset() {
	*x = DeletePersonRequest{}
	mi := &file_person_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonRequest) ProtoMessage() {}

func (x *DeletePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonRequest.ProtoReflect.Descriptor instead.
func (*DeletePersonRequest) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePersonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPersonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       uint32                 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"` // nombre, cuit, dni
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonsRequest) Reset() {
	*x = ListPersonsRequest{}
	mi := &file_person_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonsRequest) ProtoMessage() {}

func (x *ListPersonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonsRequest.ProtoReflect.Descriptor instead.
func (*ListPersonsRequest) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{8}
}

func (x *ListPersonsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPersonsRequest) GetPerPage() uint32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListPersonsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListPersonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*PersonResponse      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonsResponse) Reset() {
	*x = ListPersonsResponse{}
	mi := &file_person_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonsResponse) ProtoMessage() {}

func (x *ListPersonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonsResponse.ProtoReflect.Descriptor instead.
func (*ListPersonsResponse) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{9}
}

func (x *ListPersonsResponse) GetData() []*PersonResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListPersonsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Contactos
type AddContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonId      string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"` // required
	Payload       *AddContactPayload     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                   // required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddContactRequest) Reset() {
	*x = AddContactRequest{}
	mi := &file_person_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContactRequest) ProtoMessage() {}

func (x *AddContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContactRequest.ProtoReflect.Descriptor instead.
func (*AddContactRequest) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{10}
}

func (x *AddContactRequest) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *AddContactRequest) GetPayload() *AddContactPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AddContactPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tipo          ContactType            `protobuf:"varint,1,opt,name=tipo,proto3,enum=rem.person.v1.ContactType" json:"tipo,omitempty"` // required
	Dato          string                 `protobuf:"bytes,2,opt,name=dato,proto3" json:"dato,omitempty"`                                 // required
	IsPrimary     bool                   `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddContactPayload) Reset() {
	*x = AddContactPayload{}
	mi := &file_person_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddContactPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContactPayload) ProtoMessage() {}

func (x *AddContactPayload) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContactPayload.ProtoReflect.Descriptor instead.
func (*AddContactPayload) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{11}
}

func (x *AddContactPayload) GetTipo() ContactType {
	if x != nil {
		return x.Tipo
	}
	return ContactType_CONTACT_TYPE_UNSPECIFIED
}

func (x *AddContactPayload) GetDato() string {
	if x != nil {
		return x.Dato
	}
	return ""
}

func (x *AddContactPayload) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

type UpdateContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // required
	Tipo          ContactType            `protobuf:"varint,2,opt,name=tipo,proto3,enum=rem.person.v1.ContactType" json:"tipo,omitempty"`
	Dato          string                 `protobuf:"bytes,3,opt,name=dato,proto3" json:"dato,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContactRequest) Reset() {
	*x = UpdateContactRequest{}
	mi := &file_person_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContactRequest) ProtoMessage() {}

func (x *UpdateContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContactRequest.ProtoReflect.Descriptor instead.
func (*UpdateContactRequest) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateContactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateContactRequest) GetTipo() ContactType {
	if x != nil {
		return x.Tipo
	}
	return ContactType_CONTACT_TYPE_UNSPECIFIED
}

func (x *UpdateContactRequest) GetDato() string {
	if x != nil {
		return x.Dato
	}
	return ""
}

func (x *UpdateContactRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

type DeleteContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContactRequest) Reset() {
	*x = DeleteContactRequest{}
	mi := &file_person_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContactRequest) ProtoMessage() {}

func (x *DeleteContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContactRequest.ProtoReflect.Descriptor instead.
func (*DeleteContactRequest) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteContactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListContactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonId      string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsRequest) Reset() {
	*x = ListContactsRequest{}
	mi := &file_person_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsRequest) ProtoMessage() {}

func (x *ListContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsRequest.ProtoReflect.Descriptor instead.
func (*ListContactsRequest) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{14}
}

func (x *ListContactsRequest) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

type ListContactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Contact             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsResponse) Reset() {
	*x = ListContactsResponse{}
	mi := &file_person_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsResponse) ProtoMessage() {}

func (x *ListContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsResponse.ProtoReflect.Descriptor instead.
func (*ListContactsResponse) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{15}
}

func (x *ListContactsResponse) GetData() []*Contact {
	if x != nil {
		return x.Data
	}
	return nil
}

// --------- sub-payloads para individuo / empresa ----------
type CreateIndividual struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"` // required
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`    // required
	Dni           string                 `protobuf:"bytes,3,opt,name=dni,proto3" json:"dni,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndividual) Reset() {
	*x = CreateIndividual{}
	mi := &file_person_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndividual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndividual) ProtoMessage() {}

func (x *CreateIndividual) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndividual.ProtoReflect.Descriptor instead.
func (*CreateIndividual) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{16}
}

func (x *CreateIndividual) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateIndividual) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateIndividual) GetDni() string {
	if x != nil {
		return x.Dni
	}
	return ""
}

type UpdateIndividual struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Dni           string                 `protobuf:"bytes,3,opt,name=dni,proto3" json:"dni,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIndividual) Reset() {
	*x = UpdateIndividual{}
	mi := &file_person_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIndividual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIndividual) ProtoMessage() {}

func (x *UpdateIndividual) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIndividual.ProtoReflect.Descriptor instead.
func (*UpdateIndividual) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateIndividual) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateIndividual) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateIndividual) GetDni() string {
	if x != nil {
		return x.Dni
	}
	return ""
}

type CreateCompany struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LegalName     string                 `protobuf:"bytes,1,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"` // required
	Cuit          string                 `protobuf:"bytes,2,opt,name=cuit,proto3" json:"cuit,omitempty"`
	SocietyType   string                 `protobuf:"bytes,3,opt,name=society_type,json=societyType,proto3" json:"society_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompany) Reset() {
	*x = CreateCompany{}
	mi := &file_person_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompany) ProtoMessage() {}

func (x *CreateCompany) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompany.ProtoReflect.Descriptor instead.
func (*CreateCompany) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{18}
}

func (x *CreateCompany) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *CreateCompany) GetCuit() string {
	if x != nil {
		return x.Cuit
	}
	return ""
}

func (x *CreateCompany) GetSocietyType() string {
	if x != nil {
		return x.SocietyType
	}
	return ""
}

type UpdateCompany struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LegalName     string                 `protobuf:"bytes,1,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	Cuit          string                 `protobuf:"bytes,2,opt,name=cuit,proto3" json:"cuit,omitempty"`
	SocietyType   string                 `protobuf:"bytes,3,opt,name=society_type,json=societyType,proto3" json:"society_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompany) Reset() {
	*x = UpdateCompany{}
	mi := &file_person_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompany) ProtoMessage() {}

func (x *UpdateCompany) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompany.ProtoReflect.Descriptor instead.
func (*UpdateCompany) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateCompany) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *UpdateCompany) GetCuit() string {
	if x != nil {
		return x.Cuit
	}
	return ""
}

func (x *UpdateCompany) GetSocietyType() string {
	if x != nil {
		return x.SocietyType
	}
	return ""
}

// ───────────────────  CONTACT RESPONSE  ─────────────────────
type ContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PersonId      string                 `protobuf:"bytes,2,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	Tipo          ContactType            `protobuf:"varint,3,opt,name=tipo,proto3,enum=rem.person.v1.ContactType" json:"tipo,omitempty"`
	Dato          string                 `protobuf:"bytes,4,opt,name=dato,proto3" json:"dato,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,5,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactResponse) Reset() {
	*x = ContactResponse{}
	mi := &file_person_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactResponse) ProtoMessage() {}

func (x *ContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_person_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactResponse.ProtoReflect.Descriptor instead.
func (*ContactResponse) Descriptor() ([]byte, []int) {
	return file_person_proto_rawDescGZIP(), []int{20}
}

func (x *ContactResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContactResponse) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *ContactResponse) GetTipo() ContactType {
	if x != nil {
		return x.Tipo
	}
	return ContactType_CONTACT_TYPE_UNSPECIFIED
}

func (x *ContactResponse) GetDato() string {
	if x != nil {
		return x.Dato
	}
	return ""
}

func (x *ContactResponse) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *ContactResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_person_proto protoreflect.FileDescriptor

const file_person_proto_rawDesc = "" +
	"\n" +
	"\fperson.proto\x12\rrem.person.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x03\n" +
	"\x0ePersonResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.rem.person.v1.PersonTypeR\x04type\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\tR\taddressId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12'\n" +
	"\x04sexo\x18\x05 \x01(\x0e2\x13.rem.person.v1.SexoR\x04sexo\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\n" +
	"individual\x18\b \x01(\v2\x19.rem.person.v1.IndividualH\x00R\n" +
	"individual\x122\n" +
	"\acompany\x18\t \x01(\v2\x16.rem.person.v1.CompanyH\x00R\acompany\x122\n" +
	"\bcontacts\x18\n" +
	" \x03(\v2\x16.rem.person.v1.ContactR\bcontactsB\t\n" +
	"\adetails\"Z\n" +
	"\n" +
	"Individual\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x10\n" +
	"\x03dni\x18\x03 \x01(\tR\x03dni\"_\n" +
	"\aCompany\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x01 \x01(\tR\tlegalName\x12\x12\n" +
	"\x04cuit\x18\x02 \x01(\tR\x04cuit\x12!\n" +
	"\fsociety_type\x18\x03 \x01(\tR\vsocietyType\"\xb7\x01\n" +
	"\aContact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04tipo\x18\x02 \x01(\x0e2\x1a.rem.person.v1.ContactTypeR\x04tipo\x12\x12\n" +
	"\x04dato\x18\x03 \x01(\tR\x04dato\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf1\x02\n" +
	"\x13CreatePersonRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.rem.person.v1.PersonTypeR\x04type\x12\x1d\n" +
	"\n" +
	"address_id\x18\x02 \x01(\tR\taddressId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12'\n" +
	"\x04sexo\x18\x04 \x01(\x0e2\x13.rem.person.v1.SexoR\x04sexo\x12A\n" +
	"\n" +
	"individual\x18\x05 \x01(\v2\x1f.rem.person.v1.CreateIndividualH\x00R\n" +
	"individual\x128\n" +
	"\acompany\x18\x06 \x01(\v2\x1c.rem.person.v1.CreateCompanyH\x00R\acompany\x12<\n" +
	"\bcontacts\x18\a \x03(\v2 .rem.person.v1.AddContactPayloadR\bcontactsB\t\n" +
	"\adetails\"\x94\x02\n" +
	"\x13UpdatePersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"address_id\x18\x02 \x01(\tR\taddressId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12'\n" +
	"\x04sexo\x18\x04 \x01(\x0e2\x13.rem.person.v1.SexoR\x04sexo\x12A\n" +
	"\n" +
	"individual\x18\x05 \x01(\v2\x1f.rem.person.v1.UpdateIndividualH\x00R\n" +
	"individual\x128\n" +
	"\acompany\x18\x06 \x01(\v2\x1c.rem.person.v1.UpdateCompanyH\x00R\acompanyB\t\n" +
	"\adetails\"\"\n" +
	"\x10GetPersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13DeletePersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\x12ListPersonsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\rR\aperPage\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"^\n" +
	"\x13ListPersonsResponse\x121\n" +
	"\x04data\x18\x01 \x03(\v2\x1d.rem.person.v1.PersonResponseR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"l\n" +
	"\x11AddContactRequest\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12:\n" +
	"\apayload\x18\x02 \x01(\v2 .rem.person.v1.AddContactPayloadR\apayload\"v\n" +
	"\x11AddContactPayload\x12.\n" +
	"\x04tipo\x18\x01 \x01(\x0e2\x1a.rem.person.v1.ContactTypeR\x04tipo\x12\x12\n" +
	"\x04dato\x18\x02 \x01(\tR\x04dato\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\"\x89\x01\n" +
	"\x14UpdateContactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04tipo\x18\x02 \x01(\x0e2\x1a.rem.person.v1.ContactTypeR\x04tipo\x12\x12\n" +
	"\x04dato\x18\x03 \x01(\tR\x04dato\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\"&\n" +
	"\x14DeleteContactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x13ListContactsRequest\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\"B\n" +
	"\x14ListContactsResponse\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.rem.person.v1.ContactR\x04data\"`\n" +
	"\x10CreateIndividual\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x10\n" +
	"\x03dni\x18\x03 \x01(\tR\x03dni\"`\n" +
	"\x10UpdateIndividual\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x10\n" +
	"\x03dni\x18\x03 \x01(\tR\x03dni\"e\n" +
	"\rCreateCompany\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x01 \x01(\tR\tlegalName\x12\x12\n" +
	"\x04cuit\x18\x02 \x01(\tR\x04cuit\x12!\n" +
	"\fsociety_type\x18\x03 \x01(\tR\vsocietyType\"e\n" +
	"\rUpdateCompany\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x01 \x01(\tR\tlegalName\x12\x12\n" +
	"\x04cuit\x18\x02 \x01(\tR\x04cuit\x12!\n" +
	"\fsociety_type\x18\x03 \x01(\tR\vsocietyType\"\xdc\x01\n" +
	"\x0fContactResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tperson_id\x18\x02 \x01(\tR\bpersonId\x12.\n" +
	"\x04tipo\x18\x03 \x01(\x0e2\x1a.rem.person.v1.ContactTypeR\x04tipo\x12\x12\n" +
	"\x04dato\x18\x04 \x01(\tR\x04dato\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x05 \x01(\bR\tisPrimary\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*F\n" +
	"\n" +
	"PersonType\x12\x1b\n" +
	"\x17PERSON_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"INDIVIDUAL\x10\x01\x12\v\n" +
	"\aCOMPANY\x10\x02*9\n" +
	"\x04Sexo\x12\x14\n" +
	"\x10SEXO_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tMASCULINO\x10\x01\x12\f\n" +
	"\bFEMENINO\x10\x02*O\n" +
	"\vContactType\x12\x1c\n" +
	"\x18CONTACT_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05EMAIL\x10\x01\x12\t\n" +
	"\x05PHONE\x10\x02\x12\f\n" +
	"\bWHATSAPP\x10\x032\xf1\x05\n" +
	"\rPersonService\x12Q\n" +
	"\fCreatePerson\x12\".rem.person.v1.CreatePersonRequest\x1a\x1d.rem.person.v1.PersonResponse\x12K\n" +
	"\tGetPerson\x12\x1f.rem.person.v1.GetPersonRequest\x1a\x1d.rem.person.v1.PersonResponse\x12T\n" +
	"\vListPersons\x12!.rem.person.v1.ListPersonsRequest\x1a\".rem.person.v1.ListPersonsResponse\x12Q\n" +
	"\fUpdatePerson\x12\".rem.person.v1.UpdatePersonRequest\x1a\x1d.rem.person.v1.PersonResponse\x12J\n" +
	"\fDeletePerson\x12\".rem.person.v1.DeletePersonRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\n" +
	"AddContact\x12 .rem.person.v1.AddContactRequest\x1a\x1e.rem.person.v1.ContactResponse\x12T\n" +
	"\rUpdateContact\x12#.rem.person.v1.UpdateContactRequest\x1a\x1e.rem.person.v1.ContactResponse\x12L\n" +
	"\rDeleteContact\x12#.rem.person.v1.DeleteContactRequest\x1a\x16.google.protobuf.Empty\x12W\n" +
	"\fListContacts\x12\".rem.person.v1.ListContactsRequest\x1a#.rem.person.v1.ListContactsResponseB8Z6github.com/rem-gestion/api-suite/person/internal/pb;pbb\x06proto3"

var (
	file_person_proto_rawDescOnce sync.Once
	file_person_proto_rawDescData []byte
)

func file_person_proto_rawDescGZIP() []byte {
	file_person_proto_rawDescOnce.Do(func() {
		file_person_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_person_proto_rawDesc), len(file_person_proto_rawDesc)))
	})
	return file_person_proto_rawDescData
}

var file_person_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_person_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_person_proto_goTypes = []any{
	(PersonType)(0),               // 0: rem.person.v1.PersonType
	(Sexo)(0),                     // 1: rem.person.v1.Sexo
	(ContactType)(0),              // 2: rem.person.v1.ContactType
	(*PersonResponse)(nil),        // 3: rem.person.v1.PersonResponse
	(*Individual)(nil),            // 4: rem.person.v1.Individual
	(*Company)(nil),               // 5: rem.person.v1.Company
	(*Contact)(nil),               // 6: rem.person.v1.Contact
	(*CreatePersonRequest)(nil),   // 7: rem.person.v1.CreatePersonRequest
	(*UpdatePersonRequest)(nil),   // 8: rem.person.v1.UpdatePersonRequest
	(*GetPersonRequest)(nil),      // 9: rem.person.v1.GetPersonRequest
	(*DeletePersonRequest)(nil),   // 10: rem.person.v1.DeletePersonRequest
	(*ListPersonsRequest)(nil),    // 11: rem.person.v1.ListPersonsRequest
	(*ListPersonsResponse)(nil),   // 12: rem.person.v1.ListPersonsResponse
	(*AddContactRequest)(nil),     // 13: rem.person.v1.AddContactRequest
	(*AddContactPayload)(nil),     // 14: rem.person.v1.AddContactPayload
	(*UpdateContactRequest)(nil),  // 15: rem.person.v1.UpdateContactRequest
	(*DeleteContactRequest)(nil),  // 16: rem.person.v1.DeleteContactRequest
	(*ListContactsRequest)(nil),   // 17: rem.person.v1.ListContactsRequest
	(*ListContactsResponse)(nil),  // 18: rem.person.v1.ListContactsResponse
	(*CreateIndividual)(nil),      // 19: rem.person.v1.CreateIndividual
	(*UpdateIndividual)(nil),      // 20: rem.person.v1.UpdateIndividual
	(*CreateCompany)(nil),         // 21: rem.person.v1.CreateCompany
	(*UpdateCompany)(nil),         // 22: rem.person.v1.UpdateCompany
	(*ContactResponse)(nil),       // 23: rem.person.v1.ContactResponse
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 25: google.protobuf.Empty
}
var file_person_proto_depIdxs = []int32{
	0,  // 0: rem.person.v1.PersonResponse.type:type_name -> rem.person.v1.PersonType
	1,  // 1: rem.person.v1.PersonResponse.sexo:type_name -> rem.person.v1.Sexo
	24, // 2: rem.person.v1.PersonResponse.created_at:type_name -> google.protobuf.Timestamp
	24, // 3: rem.person.v1.PersonResponse.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 4: rem.person.v1.PersonResponse.individual:type_name -> rem.person.v1.Individual
	5,  // 5: rem.person.v1.PersonResponse.company:type_name -> rem.person.v1.Company
	6,  // 6: rem.person.v1.PersonResponse.contacts:type_name -> rem.person.v1.Contact
	2,  // 7: rem.person.v1.Contact.tipo:type_name -> rem.person.v1.ContactType
	24, // 8: rem.person.v1.Contact.created_at:type_name -> google.protobuf.Timestamp
	0,  // 9: rem.person.v1.CreatePersonRequest.type:type_name -> rem.person.v1.PersonType
	1,  // 10: rem.person.v1.CreatePersonRequest.sexo:type_name -> rem.person.v1.Sexo
	19, // 11: rem.person.v1.CreatePersonRequest.individual:type_name -> rem.person.v1.CreateIndividual
	21, // 12: rem.person.v1.CreatePersonRequest.company:type_name -> rem.person.v1.CreateCompany
	14, // 13: rem.person.v1.CreatePersonRequest.contacts:type_name -> rem.person.v1.AddContactPayload
	1,  // 14: rem.person.v1.UpdatePersonRequest.sexo:type_name -> rem.person.v1.Sexo
	20, // 15: rem.person.v1.UpdatePersonRequest.individual:type_name -> rem.person.v1.UpdateIndividual
	22, // 16: rem.person.v1.UpdatePersonRequest.company:type_name -> rem.person.v1.UpdateCompany
	3,  // 17: rem.person.v1.ListPersonsResponse.data:type_name -> rem.person.v1.PersonResponse
	14, // 18: rem.person.v1.AddContactRequest.payload:type_name -> rem.person.v1.AddContactPayload
	2,  // 19: rem.person.v1.AddContactPayload.tipo:type_name -> rem.person.v1.ContactType
	2,  // 20: rem.person.v1.UpdateContactRequest.tipo:type_name -> rem.person.v1.ContactType
	6,  // 21: rem.person.v1.ListContactsResponse.data:type_name -> rem.person.v1.Contact
	2,  // 22: rem.person.v1.ContactResponse.tipo:type_name -> rem.person.v1.ContactType
	24, // 23: rem.person.v1.ContactResponse.created_at:type_name -> google.protobuf.Timestamp
	7,  // 24: rem.person.v1.PersonService.CreatePerson:input_type -> rem.person.v1.CreatePersonRequest
	9,  // 25: rem.person.v1.PersonService.GetPerson:input_type -> rem.person.v1.GetPersonRequest
	11, // 26: rem.person.v1.PersonService.ListPersons:input_type -> rem.person.v1.ListPersonsRequest
	8,  // 27: rem.person.v1.PersonService.UpdatePerson:input_type -> rem.person.v1.UpdatePersonRequest
	10, // 28: rem.person.v1.PersonService.DeletePerson:input_type -> rem.person.v1.DeletePersonRequest
	13, // 29: rem.person.v1.PersonService.AddContact:input_type -> rem.person.v1.AddContactRequest
	15, // 30: rem.person.v1.PersonService.UpdateContact:input_type -> rem.person.v1.UpdateContactRequest
	16, // 31: rem.person.v1.PersonService.DeleteContact:input_type -> rem.person.v1.DeleteContactRequest
	17, // 32: rem.person.v1.PersonService.ListContacts:input_type -> rem.person.v1.ListContactsRequest
	3,  // 33: rem.person.v1.PersonService.CreatePerson:output_type -> rem.person.v1.PersonResponse
	3,  // 34: rem.person.v1.PersonService.GetPerson:output_type -> rem.person.v1.PersonResponse
	12, // 35: rem.person.v1.PersonService.ListPersons:output_type -> rem.person.v1.ListPersonsResponse
	3,  // 36: rem.person.v1.PersonService.UpdatePerson:output_type -> rem.person.v1.PersonResponse
	25, // 37: rem.person.v1.PersonService.DeletePerson:output_type -> google.protobuf.Empty
	23, // 38: rem.person.v1.PersonService.AddContact:output_type -> rem.person.v1.ContactResponse
	23, // 39: rem.person.v1.PersonService.UpdateContact:output_type -> rem.person.v1.ContactResponse
	25, // 40: rem.person.v1.PersonService.DeleteContact:output_type -> google.protobuf.Empty
	18, // 41: rem.person.v1.PersonService.ListContacts:output_type -> rem.person.v1.ListContactsResponse
	33, // [33:42] is the sub-list for method output_type
	24, // [24:33] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_person_proto_init() }
func file_person_proto_init() {
	if File_person_proto != nil {
		return
	}
	file_person_proto_msgTypes[0].OneofWrappers = []any{
		(*PersonResponse_Individual)(nil),
		(*PersonResponse_Company)(nil),
	}
	file_person_proto_msgTypes[4].OneofWrappers = []any{
		(*CreatePersonRequest_Individual)(nil),
		(*CreatePersonRequest_Company)(nil),
	}
	file_person_proto_msgTypes[5].OneofWrappers = []any{
		(*UpdatePersonRequest_Individual)(nil),
		(*UpdatePersonRequest_Company)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_person_proto_rawDesc), len(file_person_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_person_proto_goTypes,
		DependencyIndexes: file_person_proto_depIdxs,
		EnumInfos:         file_person_proto_enumTypes,
		MessageInfos:      file_person_proto_msgTypes,
	}.Build()
	File_person_proto = out.File
	file_person_proto_goTypes = nil
	file_person_proto_depIdxs = nil
}
